/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Invest;

import java.awt.Cursor;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URL;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author zhangxr
 */
public class MainView extends javax.swing.JFrame {

    public class CheckData {

        public CheckData(String m, String para) {
            mode = m;
            parameter = para;
        }
        public String mode;
        public String parameter;
        public String status;
        public int days;
        public double key;
        public double percent;
        public String amount;
    }

    /**
     * Creates new form StockerView
     */
    public MainView() {
        initComponents();
        setLocationRelativeTo(null);
        final URL filename = getClass().getResource("/resource/Livermore2.jpg");
        if (filename != null) {
            setIconImage(new ImageIcon(filename, "Icon").getImage());
        }

        importFile(fileIn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItemCopy = new javax.swing.JMenuItem();
        jMenuItemClear = new javax.swing.JMenuItem();
        jPanelMain = new javax.swing.JPanel();
        jLabelStockName = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePoint = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaMain = new javax.swing.JTextArea();
        jLabelSEDate = new javax.swing.JLabel();
        jLabelSEDash = new javax.swing.JLabel();
        jTextFieldSDate = new javax.swing.JTextField();
        jTextFieldEDate = new javax.swing.JTextField();
        jLabelClose = new javax.swing.JLabel();
        jButtonInvestChart = new javax.swing.JButton();
        jButtonInvestRecord = new javax.swing.JButton();
        jButtonInvestEva = new javax.swing.JButton();
        jLabelPriceFactor = new javax.swing.JLabel();
        jComboBoxPriceFactor = new javax.swing.JComboBox<>();
        jPanelSysFilter = new javax.swing.JPanel();
        jLabelPara1 = new javax.swing.JLabel();
        jLabelPara2 = new javax.swing.JLabel();
        jLabelPara3 = new javax.swing.JLabel();
        jLabelPara4 = new javax.swing.JLabel();
        jLabelDash1 = new javax.swing.JLabel();
        jLabelDash2 = new javax.swing.JLabel();
        jLabelDash3 = new javax.swing.JLabel();
        jLabelDash4 = new javax.swing.JLabel();
        jTextFieldPS1 = new javax.swing.JTextField();
        jTextFieldPE1 = new javax.swing.JTextField();
        jTextFieldPS2 = new javax.swing.JTextField();
        jTextFieldPE2 = new javax.swing.JTextField();
        jTextFieldPS3 = new javax.swing.JTextField();
        jTextFieldPE3 = new javax.swing.JTextField();
        jTextFieldPS4 = new javax.swing.JTextField();
        jTextFieldPE4 = new javax.swing.JTextField();
        jButtonFilterStart = new javax.swing.JButton();
        jButtonFilterCheck = new javax.swing.JButton();
        jButtonCheckUp = new javax.swing.JButton();
        jButtonEvaluate = new javax.swing.JButton();
        jLabelStartPoint = new javax.swing.JLabel();
        jLabelSlope = new javax.swing.JLabel();
        jLabelWinLevel = new javax.swing.JLabel();
        jLabelDiffFactor = new javax.swing.JLabel();
        jTextFieldSlope = new javax.swing.JTextField();
        jTextFieldStartPoint = new javax.swing.JTextField();
        jTextFieldWinLevel = new javax.swing.JTextField();
        jTextFieldDiffFactor = new javax.swing.JTextField();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemImport = new javax.swing.JMenuItem();
        jMenuIndex = new javax.swing.JMenu();
        jMenuItemSZZS = new javax.swing.JMenuItem();
        jMenuItemCYBZ = new javax.swing.JMenuItem();
        jMenuItemHS300 = new javax.swing.JMenuItem();
        jMenuItemZZ500 = new javax.swing.JMenuItem();
        jMenuItemSZCZ = new javax.swing.JMenuItem();
        jMenuItemSZ50 = new javax.swing.JMenuItem();
        jMenuItemZXBZ = new javax.swing.JMenuItem();
        jMenuItemYLCY = new javax.swing.JMenuItem();
        jMenuRun = new javax.swing.JMenu();
        jMenuItemDZH = new javax.swing.JMenuItem();
        jMenuItemTDX = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemAbout = new javax.swing.JMenuItem();

        jMenuItemCopy.setText("复制");
        jMenuItemCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCopyActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItemCopy);

        jMenuItemClear.setText("清除");
        jMenuItemClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClearActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItemClear);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("智能证券系统-基金定投");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelStockName.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        jLabelStockName.setForeground(new java.awt.Color(204, 0, 204));
        jLabelStockName.setText("上证指数(000001)");
        jLabelStockName.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanelMain.add(jLabelStockName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 8, -1, -1));

        jLabelDate.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabelDate.setForeground(new java.awt.Color(0, 0, 204));
        jLabelDate.setText("日期：----/--/--");
        jPanelMain.add(jLabelDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jTablePoint.getTableHeader().setFont(new java.awt.Font("微软雅黑", 0, 12));
        jTablePoint.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTablePoint.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"定投轮数", null, "平均日化率", ""},
                {"累加投入", null, "平均持仓期", null},
                {"累加产出", null, "最大投入", ""},
                {"净利润", null, "平均投入", null},
                {"总收益率", null, "最大亏损", null},
                {"测试年限", null, "最大回撤比", ""},
                {"定投笔数", "", "平均离差", null},
                {"定投时间比", null, "平均负离差", null},
                {"最长周期", "", "最小负离差", null},
                {"最长定投轮", null, "平均买入比", null},
                {"平均定投轮", null, "最大买入比", null}
            },
            new String [] {
                "统计指标", "全部交易", "统计指标", "全部交易"
            }
        ));
        jScrollPane1.setViewportView(jTablePoint);
        if (jTablePoint.getColumnModel().getColumnCount() > 0) {
            jTablePoint.getColumnModel().getColumn(0).setMaxWidth(75);
            jTablePoint.getColumnModel().getColumn(2).setMaxWidth(75);
        }

        jPanelMain.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 340, 206));

        jTextAreaMain.setColumns(20);
        jTextAreaMain.setFont(new java.awt.Font("仿宋", 0, 11)); // NOI18N
        jTextAreaMain.setRows(5);
        jTextAreaMain.setComponentPopupMenu(jPopupMenu1);
        jTextAreaMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextAreaMainMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTextAreaMain);

        jPanelMain.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 340, 80));

        jLabelSEDate.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabelSEDate.setText("日期：");
        jPanelMain.add(jLabelSEDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabelSEDash.setText("-");
        jPanelMain.add(jLabelSEDash, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        jTextFieldSDate.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTextFieldSDate.setText("----/--/--");
        jPanelMain.add(jTextFieldSDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 75, -1));

        jTextFieldEDate.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTextFieldEDate.setText("----/--/--");
        jPanelMain.add(jTextFieldEDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 75, -1));

        jLabelClose.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(250, 0, 0));
        jLabelClose.setText("收盘：--");
        jPanelMain.add(jLabelClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jButtonInvestChart.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jButtonInvestChart.setText("投资曲线");
        jButtonInvestChart.setMargin(new java.awt.Insets(2, 8, 2, 8));
        jButtonInvestChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInvestChartActionPerformed(evt);
            }
        });
        jPanelMain.add(jButtonInvestChart, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, 30));

        jButtonInvestRecord.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jButtonInvestRecord.setText("投资记录");
        jButtonInvestRecord.setMargin(new java.awt.Insets(2, 8, 2, 8));
        jButtonInvestRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInvestRecordActionPerformed(evt);
            }
        });
        jPanelMain.add(jButtonInvestRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, -1, 30));

        jButtonInvestEva.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jButtonInvestEva.setText("投资评测");
        jButtonInvestEva.setMargin(new java.awt.Insets(2, 8, 2, 8));
        jButtonInvestEva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInvestEvaActionPerformed(evt);
            }
        });
        jPanelMain.add(jButtonInvestEva, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, -1, 30));

        jLabelPriceFactor.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabelPriceFactor.setText("系数：");
        jPanelMain.add(jLabelPriceFactor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        jComboBoxPriceFactor.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jComboBoxPriceFactor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X1", "X10", "X100", "X1000" }));
        jComboBoxPriceFactor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPriceFactorActionPerformed(evt);
            }
        });
        jPanelMain.add(jComboBoxPriceFactor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        jPanelSysFilter.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "优选系统", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 12))); // NOI18N
        jPanelSysFilter.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jPanelSysFilter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPara1.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabelPara1.setText("P1:");
        jPanelSysFilter.add(jLabelPara1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 27, -1, -1));

        jLabelPara2.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabelPara2.setText("P2:");
        jPanelSysFilter.add(jLabelPara2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 27, -1, -1));

        jLabelPara3.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabelPara3.setText("P3:");
        jPanelSysFilter.add(jLabelPara3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 50, -1, -1));

        jLabelPara4.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabelPara4.setText("P4:");
        jPanelSysFilter.add(jLabelPara4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 51, -1, -1));

        jLabelDash1.setText("-");
        jPanelSysFilter.add(jLabelDash1, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 29, -1, -1));

        jLabelDash2.setText("-");
        jPanelSysFilter.add(jLabelDash2, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 30, -1, -1));

        jLabelDash3.setText("-");
        jPanelSysFilter.add(jLabelDash3, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 52, -1, -1));

        jLabelDash4.setText("-");
        jPanelSysFilter.add(jLabelDash4, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 52, -1, -1));

        jTextFieldPS1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jTextFieldPS1.setText("400");
        jPanelSysFilter.add(jTextFieldPS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 26, 30, -1));

        jTextFieldPE1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jTextFieldPE1.setText("410");
        jPanelSysFilter.add(jTextFieldPE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 26, 30, -1));

        jTextFieldPS2.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jTextFieldPS2.setText("200");
        jPanelSysFilter.add(jTextFieldPS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 26, 30, -1));

        jTextFieldPE2.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jTextFieldPE2.setText("210");
        jPanelSysFilter.add(jTextFieldPE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 26, 30, -1));

        jTextFieldPS3.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jTextFieldPS3.setText("20");
        jPanelSysFilter.add(jTextFieldPS3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 30, -1));

        jTextFieldPE3.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jTextFieldPE3.setText("60");
        jPanelSysFilter.add(jTextFieldPE3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 30, -1));

        jTextFieldPS4.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jTextFieldPS4.setText("0");
        jPanelSysFilter.add(jTextFieldPS4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 30, -1));

        jTextFieldPE4.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jTextFieldPE4.setText("30");
        jPanelSysFilter.add(jTextFieldPE4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 30, -1));

        jButtonFilterStart.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jButtonFilterStart.setText("开始");
        jButtonFilterStart.setMargin(new java.awt.Insets(2, 8, 2, 8));
        jButtonFilterStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFilterStartActionPerformed(evt);
            }
        });
        jPanelSysFilter.add(jButtonFilterStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 23, 60, -1));

        jButtonFilterCheck.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jButtonFilterCheck.setText("查看");
        jButtonFilterCheck.setEnabled(false);
        jButtonFilterCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFilterCheckActionPerformed(evt);
            }
        });
        jPanelSysFilter.add(jButtonFilterCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 48, 60, -1));

        jPanelMain.add(jPanelSysFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 310, 90));

        jButtonCheckUp.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jButtonCheckUp.setText("检测");
        jButtonCheckUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckUpActionPerformed(evt);
            }
        });
        jPanelMain.add(jButtonCheckUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, -1, 30));

        jButtonEvaluate.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jButtonEvaluate.setText("评估");
        jButtonEvaluate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEvaluateActionPerformed(evt);
            }
        });
        jPanelMain.add(jButtonEvaluate, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, 30));

        jLabelStartPoint.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabelStartPoint.setText("起始值：");
        jPanelMain.add(jLabelStartPoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));

        jLabelSlope.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabelSlope.setText("斜率(X100)：");
        jPanelMain.add(jLabelSlope, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 60, -1, -1));

        jLabelWinLevel.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabelWinLevel.setText("止赢位：");
        jPanelMain.add(jLabelWinLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, -1));

        jLabelDiffFactor.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabelDiffFactor.setText("离差因子(X10)：");
        jPanelMain.add(jLabelDiffFactor, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, -1, -1));

        jTextFieldSlope.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTextFieldSlope.setText("200");
        jPanelMain.add(jTextFieldSlope, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 40, -1));

        jTextFieldStartPoint.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTextFieldStartPoint.setText("400");
        jPanelMain.add(jTextFieldStartPoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 40, -1));

        jTextFieldWinLevel.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTextFieldWinLevel.setText("30");
        jPanelMain.add(jTextFieldWinLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 40, -1));

        jTextFieldDiffFactor.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTextFieldDiffFactor.setText("10");
        jPanelMain.add(jTextFieldDiffFactor, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 40, -1));

        getContentPane().add(jPanelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 400));

        jMenuFile.setText("文件");

        jMenuItemImport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemImport.setText("导入...");
        jMenuItemImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemImportActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemImport);

        jMenuBar.add(jMenuFile);

        jMenuIndex.setText("常用指数");

        jMenuItemSZZS.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemSZZS.setText("上证指数");
        jMenuItemSZZS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSZZSActionPerformed(evt);
            }
        });
        jMenuIndex.add(jMenuItemSZZS);

        jMenuItemCYBZ.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemCYBZ.setText("创业板指");
        jMenuItemCYBZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCYBZActionPerformed(evt);
            }
        });
        jMenuIndex.add(jMenuItemCYBZ);

        jMenuItemHS300.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemHS300.setText("沪深300");
        jMenuItemHS300.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHS300ActionPerformed(evt);
            }
        });
        jMenuIndex.add(jMenuItemHS300);

        jMenuItemZZ500.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemZZ500.setText("中证500");
        jMenuItemZZ500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemZZ500ActionPerformed(evt);
            }
        });
        jMenuIndex.add(jMenuItemZZ500);

        jMenuItemSZCZ.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemSZCZ.setText("深证成指");
        jMenuItemSZCZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSZCZActionPerformed(evt);
            }
        });
        jMenuIndex.add(jMenuItemSZCZ);

        jMenuItemSZ50.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemSZ50.setText("上证50");
        jMenuItemSZ50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSZ50ActionPerformed(evt);
            }
        });
        jMenuIndex.add(jMenuItemSZ50);

        jMenuItemZXBZ.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_7, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemZXBZ.setText("中小板指");
        jMenuItemZXBZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemZXBZActionPerformed(evt);
            }
        });
        jMenuIndex.add(jMenuItemZXBZ);

        jMenuItemYLCY.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_8, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemYLCY.setText("养老产业");
        jMenuItemYLCY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemYLCYActionPerformed(evt);
            }
        });
        jMenuIndex.add(jMenuItemYLCY);

        jMenuBar.add(jMenuIndex);

        jMenuRun.setText("运行");

        jMenuItemDZH.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemDZH.setText("大智慧");
        jMenuItemDZH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDZHActionPerformed(evt);
            }
        });
        jMenuRun.add(jMenuItemDZH);

        jMenuItemTDX.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemTDX.setText("通达信");
        jMenuItemTDX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTDXActionPerformed(evt);
            }
        });
        jMenuRun.add(jMenuItemTDX);

        jMenuBar.add(jMenuRun);

        jMenuHelp.setText("帮助");

        jMenuItemAbout.setText("关于");
        jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItemAbout);

        jMenuBar.add(jMenuHelp);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemImportActionPerformed
        importFile(null);
    }//GEN-LAST:event_jMenuItemImportActionPerformed

    private void jMenuItemSZZSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSZZSActionPerformed
        importFile("data\\上证指数.txt");
    }//GEN-LAST:event_jMenuItemSZZSActionPerformed

    private void jMenuItemCYBZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCYBZActionPerformed
        importFile("data\\创业板指.txt");
    }//GEN-LAST:event_jMenuItemCYBZActionPerformed

    private void jMenuItemHS300ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHS300ActionPerformed
        importFile("data\\沪深300.txt");
    }//GEN-LAST:event_jMenuItemHS300ActionPerformed

    private void jMenuItemZZ500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemZZ500ActionPerformed
        importFile("data\\中证500.txt");
    }//GEN-LAST:event_jMenuItemZZ500ActionPerformed

    private void jMenuItemSZCZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSZCZActionPerformed
        importFile("data\\深证成指.txt");
    }//GEN-LAST:event_jMenuItemSZCZActionPerformed

    private void jMenuItemSZ50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSZ50ActionPerformed
        importFile("data\\上证50.txt");
    }//GEN-LAST:event_jMenuItemSZ50ActionPerformed

    private void jMenuItemZXBZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemZXBZActionPerformed
        importFile("data\\中小板指.txt");
    }//GEN-LAST:event_jMenuItemZXBZActionPerformed

    private void jMenuItemYLCYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemYLCYActionPerformed
        importFile("data\\养老产业.txt");
    }//GEN-LAST:event_jMenuItemYLCYActionPerformed

    private void jMenuItemDZHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDZHActionPerformed
        runExeFile("C:\\dzh365\\dzh2.exe");
    }//GEN-LAST:event_jMenuItemDZHActionPerformed

    private void jMenuItemTDXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTDXActionPerformed
        runExeFile("C:\\new_tdx\\TdxW.exe");
    }//GEN-LAST:event_jMenuItemTDXActionPerformed

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
        JOptionPane.showMessageDialog(new JFrame(), "智能证券系统-基金定投 V16.10\n版权所有(C) 张向荣(Aioros Zhang)");
    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    private void jTextAreaMainMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextAreaMainMouseReleased
        if (evt.isPopupTrigger()) {
            jPopupMenu1.show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jTextAreaMainMouseReleased

    private void jMenuItemClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClearActionPerformed
        jTextAreaMain.setText("");
    }//GEN-LAST:event_jMenuItemClearActionPerformed

    private void jMenuItemCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCopyActionPerformed
        jTextAreaMain.selectAll();
        jTextAreaMain.copy();
    }//GEN-LAST:event_jMenuItemCopyActionPerformed

    private void jButtonInvestChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInvestChartActionPerformed
        TradeChart tc = new TradeChart(this, false, this);
    }//GEN-LAST:event_jButtonInvestChartActionPerformed

    private void jButtonInvestRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInvestRecordActionPerformed
        if (evaluated) {
            TradeTable tradeTable = new TradeTable(this, false, this);
        } else {
            JOptionPane.showMessageDialog(this, "请先进行评测再查看交易记录");
        }
    }//GEN-LAST:event_jButtonInvestRecordActionPerformed

    private void jButtonInvestEvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInvestEvaActionPerformed
        boolean ret = false;
        dateProcess();
        if (investDays == 0) {
            return;
        }
        getInvestMode();
        int p1 = 0, p2 = 0, p3 = 0, p4 = 0;
        String[] words = investPara.split(",");
        p1 = Integer.parseInt(words[0]);
        p2 = Integer.parseInt(words[1]);
        p3 = Integer.parseInt(words[2]);
        p4 = Integer.parseInt(words[3]);

        strategy = new Strategy(this);
        ret = strategy.sysInvestEva(p1, p2, p3, p4);
        if (!ret) {
            JOptionPane.showMessageDialog(new JFrame(), "无效的参数设置！");
            return;
        }
        SystemReport sr = updateSystemReport(strategy);
        updateTable(sr);
        updateMarket(eIdx);
        evaluated = true;
    }//GEN-LAST:event_jButtonInvestEvaActionPerformed

    private void jButtonFilterStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFilterStartActionPerformed
        long time = System.currentTimeMillis();
        jTextAreaMain.setText("");
        dateProcess();
        if (investDays == 0) {
            return;
        }
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        SystemReport sr;
        ArrayList<SystemReport> srList = new ArrayList<>();
        int ps1 = Integer.parseInt(jTextFieldPS1.getText());
        int pe1 = Integer.parseInt(jTextFieldPE1.getText());
        int ps2 = Integer.parseInt(jTextFieldPS2.getText());
        int pe2 = Integer.parseInt(jTextFieldPE2.getText());
        int ps3 = Integer.parseInt(jTextFieldPS3.getText());
        int pe3 = Integer.parseInt(jTextFieldPE3.getText());
        int ps4 = Integer.parseInt(jTextFieldPS4.getText());
        int pe4 = Integer.parseInt(jTextFieldPE4.getText());

        for (int i = ps1; i <= pe1; i++) {
            for (int j = ps2; j <= pe2; j++) {
                for (int k = ps3; k <= pe3; k++) {
                    for (int l = ps4; l <= pe4; l++) {
                        strategy = new Strategy(this);
                        if (strategy.sysInvestEva(i, j, k, l)) {
                            String para = String.format("%d,%d,%d,%d", i, j, k, l);
                            sr = updateSimpleReport(para, strategy);
                            srList.add(sr);
                        }
                    }
                }
            }
        }
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));

        jButtonFilterCheck.setEnabled(true);
        Collections.sort(srList, (SystemReport arg0, SystemReport arg1) -> new Float(arg1.netProfit).compareTo(arg0.netProfit));
        rankTable = new RankTable(this, false, this, srList);

        time = System.currentTimeMillis() - time;
        float excTime = (float) time / 1000;
        System.out.println("Elapsed time: " + excTime + "s");
    }//GEN-LAST:event_jButtonFilterStartActionPerformed

    private void jButtonFilterCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFilterCheckActionPerformed
        rankTable.setVisible(true);
    }//GEN-LAST:event_jButtonFilterCheckActionPerformed

    private void jComboBoxPriceFactorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPriceFactorActionPerformed
        for (int i = 0; i < rows; i++) {
            double zoomPrice = closeList.get(i) * Math.pow(10, jComboBoxPriceFactor.getSelectedIndex());
            priceList.set(i, zoomPrice);
        }
    }//GEN-LAST:event_jComboBoxPriceFactorActionPerformed

    private void jButtonCheckUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckUpActionPerformed
        ArrayList<String> modelList = new ArrayList<>();
        chkDataList = new ArrayList<>();

        try {
            File file = new File("ini/" + stockName + ".ini");
            if (!file.exists()) {
                JOptionPane.showMessageDialog(new JFrame(), "没有对应的\"" + stockName + ".ini\"文件！");
                return;
            }
            InputStreamReader isr = new InputStreamReader(new FileInputStream(file), "gbk");
            BufferedReader br = new BufferedReader(isr);
            String line;
            while ((line = br.readLine()) != null) {
                if (line.matches("^[A-Z].*")) {
                    modelList.add(line);
                }
            }
            br.close();
            isr.close();
        } catch (IOException | NumberFormatException e) {
            e.printStackTrace();
            return;
        }

        for (String line : modelList) {
            String[] words = line.split(":");
            String mode = words[0];
            String para = words[1];
            switch (mode) {
                case "MA":
                    sysMAChk(para);
                    break;
                case "BAR":
                case "DIF":
                    //sysMACDChk(mode, para);
                    break;
                default:
                    break;
            }
        }

        CheckTable ct = new CheckTable(this, false, this);
    }//GEN-LAST:event_jButtonCheckUpActionPerformed

    private void jButtonEvaluateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEvaluateActionPerformed
        ArrayList<String> modelList = new ArrayList<>();
        chkDataList = new ArrayList<>();

        try {
            File file = new File("ini/" + stockName + ".ini");
            if (!file.exists()) {
                JOptionPane.showMessageDialog(new JFrame(), "没有对应的\"" + stockName + ".ini\"文件！");
                return;
            }
            InputStreamReader isr = new InputStreamReader(new FileInputStream(file), "gbk");
            BufferedReader br = new BufferedReader(isr);
            String line;
            while ((line = br.readLine()) != null) {
                if (line.matches("^[A-Z].*")) {
                    modelList.add(line);
                }
            }
            br.close();
            isr.close();
        } catch (IOException | NumberFormatException e) {
            e.printStackTrace();
            return;
        }

        dateProcess();
        if (investDays == 0) {
            return;
        }
        SystemReport sr;
        ArrayList<SystemReport> srList = new ArrayList<>();

        int p1 = 0, p2 = 0, p3 = 0;
        for (String line : modelList) {
            String[] words = line.split(":");
            String mode = words[0];
            String paras[] = words[1].split(" ");
            String[] ps = paras[0].split(",");
            try {
                p1 = Integer.parseInt(ps[0]);
                p2 = Integer.parseInt(ps[1]);
                p3 = Integer.parseInt(ps[2]);
            } catch (Exception e) {
            }
            switch (mode) {
                case "MA":
//                    if (sysInvestEva(p1, p2)) {
//                        String para = String.format("%d,%d", p1, p2);
//                        sr = updateSimpleReport(mode, para, strategy);
//                        srList.add(sr);
//                    }
                    break;
                default:
                    break;
            }
        }
        rankTable = new RankTable(this, false, this, srList);
    }//GEN-LAST:event_jButtonEvaluateActionPerformed

    /**
     ********************* Start of User-defined function ********************
     */
    protected void importFile(String fileName) {
        if (fileName == null) {
            JFileChooser chooser = new JFileChooser("data/");
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Data File (*.txt)", "txt");
            chooser.setFileFilter(filter);
            chooser.setDialogTitle("Select Data File");
            int ret = chooser.showOpenDialog(this);
            if (ret == JFileChooser.APPROVE_OPTION) {
                fileIn = chooser.getSelectedFile().getPath();
                fileOut = fileIn.substring(0, fileIn.length() - 4) + "_测试日志.txt";
            } else {
                return;
            }
        } else {
            fileIn = fileName;
            fileOut = fileIn.substring(0, fileIn.length() - 4) + "_测试日志.txt";
        }

        try {
            File file = new File(fileIn);
            InputStreamReader isr = new InputStreamReader(new FileInputStream(file), "gbk");
            BufferedReader br = new BufferedReader(isr);
            String[] words = br.readLine().split("\t");
            stockName = words[1];
            stockCode = words[0].replaceAll("[\\pP\\p{Punct}]", "");
            jLabelStockName.setText(stockName + "(" + stockCode + ")");
            words = br.readLine().split("\t");
            column = words.length;
            dateList = new ArrayList<>();
            openList = new ArrayList<>();
            closeList = new ArrayList<>();
            priceList = new ArrayList<>();
            String line;
            while ((line = br.readLine()) != null) {
                words = line.split("\t");
                dateList.add(words[0]);
                openList.add(Double.parseDouble(words[1]));
                closeList.add(Double.parseDouble(words[4]));
                priceList.add(Double.parseDouble(words[4]));
            }
            rows = dateList.size();
            br.close();
            isr.close();
        } catch (IOException | NumberFormatException e) {
            e.printStackTrace();
        }
        jTextFieldSDate.setText(dateList.get(0));
        jTextFieldEDate.setText(dateList.get(rows - 1));
        updateMarket(rows - 1);
        evaluated = false;
    }

    private void sysMAChk(String para) {
        String[] paras = para.split(" ");
        String para0 = paras[0];
        String[] ps = para0.split(",");
        int mas = Integer.parseInt(ps[0]);
        int mal = Integer.parseInt(ps[1]);
        CheckData chkData = new CheckData("MA", para0);
        chkData.amount = paras[1];

//        MALine ma = new MALine(priceList);
//        strategy = new Strategy(this);
//        strategy.ma = ma;
//        ArrayList<Double> masList = ma.getMAList(mas);
//        ArrayList<Double> malList = ma.getMAList(mal);
        for (int i = 0; i < rows; i++) {
            //strategy.maCrossTrade(i, masList, malList);
        }
//        bpIndexList = strategy.bpIdxList;
//        spIndexList = strategy.spIdxList;
//        if (bpIndexList.size() > spIndexList.size()) {
//            chkData.status = "持有";
//            chkData.days = daysBetween(bpIndexList.get(bpIndexList.size() - 1), rows - 1);
//        } else {
//            chkData.status = "清空";
//            chkData.days = daysBetween(spIndexList.get(spIndexList.size() - 1), rows - 1);
//        }
//
//        //chkData.key = ma.getMAKey(mas, mal);
//        chkData.percent = 100 * (chkData.key - priceList.get(rows - 1)) / priceList.get(rows - 1);
//        chkDataList.add(chkData);
    }

    public void investParaEva(String para) {
        String[] paras = para.replaceAll(" ", "").split(",");
        jTextFieldStartPoint.setText(paras[0]);
        jTextFieldSlope.setText(paras[1]);
        jTextFieldWinLevel.setText(paras[2]);
        jTextFieldDiffFactor.setText(paras[3]);

        jButtonInvestEva.doClick();
    }

    public void getInvestMode() {
        investPara = jTextFieldStartPoint.getText() + "," + jTextFieldSlope.getText() + "," + jTextFieldWinLevel.getText() + "," + jTextFieldDiffFactor.getText();
    }

    private void dateProcess() {
        String start = jTextFieldSDate.getText();
        String end = jTextFieldEDate.getText();
        if ((end.compareTo(start) <= 0)) {
            JOptionPane.showMessageDialog(this, "起始日期必须早于结束日期！");
            investDays = 0;
            return;
        }

        sIdx = -1;
        eIdx = 0;
        for (int i = 0; i < rows; i++) {
            if ((dateList.get(i).compareTo(start) >= 0) && (dateList.get(i).compareTo(end) <= 0)) {
                if (sIdx == -1) {
                    sIdx = i;
                }
                eIdx = i;
            }
        }
        testYears = (double) daysBetween(sIdx, eIdx) / 365.25;
        investDays = eIdx - sIdx + 1;
    }

    protected void updateMarket(int idx) {
        jLabelDate.setText("日期：" + dateList.get(idx));
        double margin = closeList.get(idx) - closeList.get(idx - 1);
        double ratio = 100 * (closeList.get(idx) - closeList.get(idx - 1)) / closeList.get(idx - 1);
        if (margin > 0) {
            jLabelClose.setForeground(new java.awt.Color(250, 0, 0));
            jLabelClose.setText(String.format("收盘：%s  上涨：%.2f/%5.2f%%", closeList.get(idx), margin, ratio));
        } else {
            jLabelClose.setForeground(new java.awt.Color(0, 150, 0));
            jLabelClose.setText(String.format("收盘：%s  下跌：%.2f/%5.2f%%", closeList.get(idx), margin, ratio));
        }
    }

    protected SystemReport updateSystemReport(Strategy stg) {
        SystemReport sr = new SystemReport();

        sr.investRounds = stg.getInvestRounds();
        sr.addInvest = (float) stg.getAddInvest();
        sr.addOutput = (float) stg.getAddOutput();
        sr.netProfit = (float) stg.getNetProfit();
        sr.yieldRate = (float) stg.getYieldRate();
        sr.testYears = (float) testYears;
        sr.investCounts = stg.getInvestCounts();
        sr.investTimeRatio = (float) stg.getInvestTimeRatio();
        sr.maxRoundTime = (float) stg.getMaxRoundTime();
        sr.maxInvestCount = (float) stg.getMaxInvestCount();
        sr.meanInvestCount = (float) stg.getMeanInvestCount();

        sr.meanDailyRate = (float) stg.getMeanDailyRate();
        sr.meanPositionDays = (float) stg.getMeanPositionDays();
        sr.maxInvest = (float) stg.getMaxInvest();
        sr.meanInvest = (float) stg.getMeanInvest();
        sr.maxLoss = (float) stg.getMaxLoss();
        sr.maxLossRatio = (float) stg.getMaxLossRatio();
        sr.meanDiffRate = (float) stg.getMeanDiffRate();
        sr.meanNegaDiffRate = (float) stg.getMeanNegaDiffRate();
        sr.minDiffRate = (float) stg.getMinDiffRate();
        sr.meanInvestRate = (float) stg.getMeanInvestRate();
        sr.maxInvestRate = (float) stg.getMaxInvestRate();

        return sr;
    }

    protected SystemReport updateSimpleReport(String para, Strategy stg) {
        SystemReport sr = new SystemReport(para);

        sr.addInvest = (float) stg.getAddInvest();
        sr.netProfit = (float) stg.getNetProfit();
        sr.meanDailyRate = (float) stg.getMeanDailyRate();
        sr.meanPositionDays = (float) stg.getMeanPositionDays();
        sr.maxInvest = (float) stg.getMaxInvest();
        sr.maxRoundTime = (float) stg.getMaxRoundTime();
        sr.maxLoss = (float) stg.getMaxLoss();

        return sr;
    }

    protected void updateTable(SystemReport sr) {
        jTablePoint.setValueAt("定投轮数", 0, 0);
        jTablePoint.setValueAt(sr.investRounds + "轮", 0, 1);
        jTablePoint.setValueAt("累加投入", 1, 0);
        jTablePoint.setValueAt(sr.addInvest + "元", 1, 1);
        jTablePoint.setValueAt("累加产出", 2, 0);
        jTablePoint.setValueAt(sr.addOutput + "元", 2, 1);
        jTablePoint.setValueAt("净利润", 3, 0);
        jTablePoint.setValueAt(sr.netProfit + "元", 3, 1);
        jTablePoint.setValueAt("总收益率", 4, 0);
        jTablePoint.setValueAt(sr.yieldRate + "%", 4, 1);
        jTablePoint.setValueAt("测试年限", 5, 0);
        jTablePoint.setValueAt(sr.testYears + "年", 5, 1);
        jTablePoint.setValueAt("定投笔数", 6, 0);
        jTablePoint.setValueAt(sr.investCounts + "笔", 6, 1);
        jTablePoint.setValueAt("定投时间比", 7, 0);
        jTablePoint.setValueAt(sr.investTimeRatio + "%", 7, 1);
        jTablePoint.setValueAt("最长周期", 8, 0);
        jTablePoint.setValueAt(sr.maxRoundTime + "年", 8, 1);
        jTablePoint.setValueAt("最长定投轮", 9, 0);
        jTablePoint.setValueAt(sr.maxInvestCount + "次", 9, 1);
        jTablePoint.setValueAt("平均定投轮", 10, 0);
        jTablePoint.setValueAt(sr.meanInvestCount + "次", 10, 1);

        jTablePoint.setValueAt("平均日化率", 0, 2);
        jTablePoint.setValueAt("万" + sr.meanDailyRate, 0, 3);
        jTablePoint.setValueAt("平均持仓期", 1, 2);
        jTablePoint.setValueAt(sr.meanPositionDays + "天", 1, 3);
        jTablePoint.setValueAt("最大投入", 2, 2);
        jTablePoint.setValueAt(sr.maxInvest + "元", 2, 3);
        jTablePoint.setValueAt("平均投入", 3, 2);
        jTablePoint.setValueAt(sr.meanInvest + "元", 3, 3);
        jTablePoint.setValueAt("最大亏损", 4, 2);
        jTablePoint.setValueAt(sr.maxLoss + "元", 4, 3);
        jTablePoint.setValueAt("最大回撤比", 5, 2);
        jTablePoint.setValueAt(sr.maxLossRatio + "%", 5, 3);
        jTablePoint.setValueAt("平均离差", 6, 2);
        jTablePoint.setValueAt(sr.meanDiffRate, 6, 3);
        jTablePoint.setValueAt("平均负离差", 7, 2);
        jTablePoint.setValueAt(sr.meanNegaDiffRate, 7, 3);
        jTablePoint.setValueAt("最小负离差", 8, 2);
        jTablePoint.setValueAt(sr.minDiffRate, 8, 3);
        jTablePoint.setValueAt("平均买入比", 9, 2);
        jTablePoint.setValueAt(sr.meanInvestRate, 9, 3);
        jTablePoint.setValueAt("最大买入比", 10, 2);
        jTablePoint.setValueAt(sr.maxInvestRate, 10, 3);
    }

    public void msgLogger(String str) {
        jTextAreaMain.append(str + System.getProperty("line.separator"));
    }

    public void fileLogger(String str) {
        if (fileWriter != null) {
            try {
                fileWriter.write(str + System.getProperty("line.separator"));
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }

    public void runExeFile(String file) {
        try {
            Runtime rt = Runtime.getRuntime();
            File exeFile = new File(file);
            if (exeFile.exists()) {
                String cmd = "cmd.exe /c " + file;
                rt.exec(cmd);
            } else {
                JOptionPane.showMessageDialog(new JFrame(), "请先安装相关软件到根目录！");
            }
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    public int daysBetween(int idxs, int idxe) {
        String sdate = dateList.get(idxs);
        String edate = dateList.get(idxe);
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        Calendar cal = Calendar.getInstance();
        long between_days = 0;
        try {
            cal.setTime(dateFormat.parse(sdate));
            long time1 = cal.getTimeInMillis();
            cal.setTime(dateFormat.parse(edate));
            long time2 = cal.getTimeInMillis();
            between_days = (time2 - time1) / (1000 * 3600 * 24);
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        return Integer.parseInt(String.valueOf(between_days));
    }

    public int daysBetween(String sdate, String edate) {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        Calendar cal = Calendar.getInstance();
        long between_days = 0;
        try {
            cal.setTime(dateFormat.parse(sdate));
            long time1 = cal.getTimeInMillis();
            cal.setTime(dateFormat.parse(edate));
            long time2 = cal.getTimeInMillis();
            between_days = (time2 - time1) / (1000 * 3600 * 24);
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        return Integer.parseInt(String.valueOf(between_days));
    }

    private String fileIn = "data\\上证指数_周.txt";
    private String fileOut = "data\\上证指数_测试日志.txt";
    public FileWriter fileWriter;

    public String stockName = "上证指数";
    public String stockCode = "000001";
    public int column = 0;
    public int rows = 0;
    public ArrayList<String> dateList;
    public ArrayList<Double> openList;
    public ArrayList<Double> closeList;
    public ArrayList<Double> priceList;
    public ArrayList<Double> fundList;
    public ArrayList<Integer> bpIndexList;
    public ArrayList<Integer> spIndexList;
    public int sIdx = -1;
    public int eIdx = 0;
    public int investDays = 0;
    public double testYears = 0;

    public Strategy strategy;
    public boolean evaluated = false;
    public RankTable rankTable;
    public int brmMode = 0;
    public String tradeMode;
    public String investPara;
    public ArrayList<CheckData> chkDataList;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCheckUp;
    private javax.swing.JButton jButtonEvaluate;
    private javax.swing.JButton jButtonFilterCheck;
    private javax.swing.JButton jButtonFilterStart;
    private javax.swing.JButton jButtonInvestChart;
    private javax.swing.JButton jButtonInvestEva;
    private javax.swing.JButton jButtonInvestRecord;
    private javax.swing.JComboBox<String> jComboBoxPriceFactor;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelDash1;
    private javax.swing.JLabel jLabelDash2;
    private javax.swing.JLabel jLabelDash3;
    private javax.swing.JLabel jLabelDash4;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelDiffFactor;
    private javax.swing.JLabel jLabelPara1;
    private javax.swing.JLabel jLabelPara2;
    private javax.swing.JLabel jLabelPara3;
    private javax.swing.JLabel jLabelPara4;
    private javax.swing.JLabel jLabelPriceFactor;
    private javax.swing.JLabel jLabelSEDash;
    private javax.swing.JLabel jLabelSEDate;
    private javax.swing.JLabel jLabelSlope;
    private javax.swing.JLabel jLabelStartPoint;
    private javax.swing.JLabel jLabelStockName;
    private javax.swing.JLabel jLabelWinLevel;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenu jMenuIndex;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemCYBZ;
    private javax.swing.JMenuItem jMenuItemClear;
    private javax.swing.JMenuItem jMenuItemCopy;
    private javax.swing.JMenuItem jMenuItemDZH;
    private javax.swing.JMenuItem jMenuItemHS300;
    private javax.swing.JMenuItem jMenuItemImport;
    private javax.swing.JMenuItem jMenuItemSZ50;
    private javax.swing.JMenuItem jMenuItemSZCZ;
    private javax.swing.JMenuItem jMenuItemSZZS;
    private javax.swing.JMenuItem jMenuItemTDX;
    private javax.swing.JMenuItem jMenuItemYLCY;
    private javax.swing.JMenuItem jMenuItemZXBZ;
    private javax.swing.JMenuItem jMenuItemZZ500;
    private javax.swing.JMenu jMenuRun;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelSysFilter;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablePoint;
    private javax.swing.JTextArea jTextAreaMain;
    private javax.swing.JTextField jTextFieldDiffFactor;
    private javax.swing.JTextField jTextFieldEDate;
    private javax.swing.JTextField jTextFieldPE1;
    private javax.swing.JTextField jTextFieldPE2;
    private javax.swing.JTextField jTextFieldPE3;
    private javax.swing.JTextField jTextFieldPE4;
    private javax.swing.JTextField jTextFieldPS1;
    private javax.swing.JTextField jTextFieldPS2;
    private javax.swing.JTextField jTextFieldPS3;
    private javax.swing.JTextField jTextFieldPS4;
    private javax.swing.JTextField jTextFieldSDate;
    private javax.swing.JTextField jTextFieldSlope;
    private javax.swing.JTextField jTextFieldStartPoint;
    private javax.swing.JTextField jTextFieldWinLevel;
    // End of variables declaration//GEN-END:variables
}
