/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Trader;

import Trader.MainView.CheckData;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author zhangxr
 */
public class CheckTable extends javax.swing.JDialog {

    /**
     * Creates new form CheckTable
     */
    public CheckTable(java.awt.Frame parent, boolean modal, MainView mv) {
        super(parent, modal);
        initComponents();
        mainView = mv;
        outputStockInfo();

        ArrayList<CheckData> list = mv.chkDataList;
        int size = list.size();
        String[][] tableContent = new String[size][6];
        for (int i = 0; i < size; i++) {
            tableContent[i][0] = list.get(i).mode;
            tableContent[i][1] = list.get(i).parameter;
            tableContent[i][2] = list.get(i).status;
            tableContent[i][3] = list.get(i).days + "天";
            tableContent[i][4] = String.format("%.2f", list.get(i).key);
            tableContent[i][5] = String.format("%.2f%%", list.get(i).percent);;
        }
        jTableCheck.getTableHeader().setFont(new java.awt.Font("微软雅黑", 0, 13));
        jTableCheck.setModel(new javax.swing.table.DefaultTableModel(
                tableContent,
                new String[]{
                    "模式", "参数", "状态", "持续时间", "关键点", "百分比"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false, false
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jTableCheck.setRowHeight(20);
        jScrollPaneCheck.setViewportView(jTableCheck);
        setTableRowColor(jTableCheck, new Color(200, 0, 0), new Color(0, 130, 2));

        setPreferredSize(new java.awt.Dimension(535, 20 * size + 110));
        jScrollPaneCheck.setPreferredSize(new java.awt.Dimension(500, 20 * size + 31));
        getContentPane().add(jScrollPaneCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));
        pack();
        setLocationRelativeTo(parent);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelName = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabelRange = new javax.swing.JLabel();
        jScrollPaneCheck = new javax.swing.JScrollPane();
        jTableCheck = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("行情状态");
        setPreferredSize(new java.awt.Dimension(535, 130));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelName.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabelName.setForeground(new java.awt.Color(102, 0, 0));
        jLabelName.setText("上证指数");
        getContentPane().add(jLabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabelDate.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabelDate.setForeground(new java.awt.Color(0, 0, 102));
        jLabelDate.setText("日期：20--/--/--");
        getContentPane().add(jLabelDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabelClose.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(51, 51, 0));
        jLabelClose.setText("收盘：----");
        getContentPane().add(jLabelClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jLabelRange.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabelRange.setText("涨跌：----");
        getContentPane().add(jLabelRange, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        jScrollPaneCheck.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N

        jTableCheck.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTableCheck.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTableCheck.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "模式", "参数", "状态", "持续时间", "关键点", "百分比"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCheck.setRowHeight(20);
        jTableCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCheckMouseClicked(evt);
            }
        });
        jScrollPaneCheck.setViewportView(jTableCheck);

        getContentPane().add(jScrollPaneCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 500, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableCheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCheckMouseClicked
        if (evt.getClickCount() > 1) {
            jTableCheck.setRowSelectionAllowed(true);
            int index = jTableCheck.getSelectedRow();
            String mode = (String) jTableCheck.getValueAt(index, 0);
            String para = (String) jTableCheck.getValueAt(index, 1);
            mainView.tradeModeEva(mode, para);
        } else {
            jTableCheck.setRowSelectionAllowed(false);
        }
    }//GEN-LAST:event_jTableCheckMouseClicked

    public static void setTableRowColor(javax.swing.JTable Table, final Color color1, final Color color2) {
        try {
            DefaultTableCellRenderer tcr = new DefaultTableCellRenderer() {
                @Override
                public Component getTableCellRendererComponent(javax.swing.JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                    String status = (String) Table.getValueAt(row, 2);
                    if (status.equals("买入")) {
                        setForeground(color1);
                    } else {
                        setForeground(color2);
                    }
                    return super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                }
            };
            for (int i = 0; i < Table.getColumnCount(); i++) {
                Table.getColumnModel().getColumn(i).setCellRenderer(tcr);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void outputStockInfo() {
        int idx = mainView.rows - 1;
        jLabelName.setText(mainView.stockName + "(" + mainView.stockCode + ")");
        jLabelDate.setText("日期：" + mainView.dateList.get(idx));
        jLabelClose.setText("收盘：" + String.format("%s", mainView.closeList.get(idx)));
        double margin = mainView.closeList.get(idx) - mainView.closeList.get(idx - 1);
        double ratio = 100 * (mainView.closeList.get(idx) - mainView.closeList.get(idx - 1)) / mainView.closeList.get(idx - 1);
        if (margin > 0) {
            jLabelRange.setForeground(new java.awt.Color(250, 0, 0));
            jLabelRange.setText(String.format("上涨：%.2f/%5.2f%%", margin, ratio));
        } else {
            jLabelRange.setForeground(new java.awt.Color(0, 150, 0));
            jLabelRange.setText(String.format("下跌：%.2f/%5.2f%%", margin, ratio));
        }
    }

    private MainView mainView;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelRange;
    private javax.swing.JScrollPane jScrollPaneCheck;
    private javax.swing.JTable jTableCheck;
    // End of variables declaration//GEN-END:variables
}
