/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Trader;

import Trader.MainView.CheckData;
import java.util.ArrayList;

/**
 *
 * @author zhangxr
 */
public class CheckTable extends javax.swing.JDialog {

    /**
     * Creates new form CheckTable
     */
    public CheckTable(java.awt.Frame parent, boolean modal, ArrayList<CheckData> list) {
        super(parent, modal);
        initComponents();

        int size = list.size();
        String[][] tableContent = new String[size][6];
        for (int i = 0; i < size; i++) {
            tableContent[i][0] = list.get(i).mode;
            tableContent[i][1] = list.get(i).parameter;
            tableContent[i][2] = list.get(i).status;
            tableContent[i][3] = list.get(i).days + "天";
            tableContent[i][4] = String.format("%.2f", list.get(i).key);
            tableContent[i][5] = String.format("%.2f%%", list.get(i).percent);;
        }
        jTableCheck.getTableHeader().setFont(new java.awt.Font("微软雅黑", 0, 13));
        jTableCheck.setModel(new javax.swing.table.DefaultTableModel(
                tableContent,
                new String[]{
                    "模式", "参数", "状态", "持续时间", "关键点", "百分比"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false, false
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jTableCheck.setRowHeight(20);
        jScrollPaneCheck.setViewportView(jTableCheck);

        setPreferredSize(new java.awt.Dimension(535, 20 * size + 90));
        jScrollPaneCheck.setPreferredSize(new java.awt.Dimension(500, 20 * size + 31));
        getContentPane().add(jScrollPaneCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        pack();
        setLocationRelativeTo(parent);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneCheck = new javax.swing.JScrollPane();
        jTableCheck = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("行情状态");
        setPreferredSize(new java.awt.Dimension(535, 110));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPaneCheck.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N

        jTableCheck.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTableCheck.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTableCheck.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "模式", "参数", "状态", "持续时间", "关键点", "百分比"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCheck.setRowHeight(20);
        jScrollPaneCheck.setViewportView(jTableCheck);

        getContentPane().add(jScrollPaneCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 500, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPaneCheck;
    private javax.swing.JTable jTableCheck;
    // End of variables declaration//GEN-END:variables
}
