/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Stagging;

import java.awt.Cursor;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author zhangxr
 */
public class MainView extends javax.swing.JFrame {

    public class CheckData {

        public CheckData(String m, String para) {
            mode = m;
            parameter = para;
        }
        public String mode;
        public String parameter;
        public String status;
        public int days;
        public double key;
        public double percent;
        public String amount;
    }

    /**
     * Creates new form StockerView
     */
    public MainView() {
        initComponents();
        setLocationRelativeTo(null);
        final URL filename = getClass().getResource("/resource/Livermore3.jpg");
        if (filename != null) {
            setIconImage(new ImageIcon(filename, "Icon").getImage());
        }
        importData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanelMain = new javax.swing.JPanel();
        jPanelCongfig1 = new javax.swing.JPanel();
        jRadioButtonSuperPurchaseMultiples1 = new javax.swing.JRadioButton();
        jRadioButtonLuckRate1 = new javax.swing.JRadioButton();
        jRadioButtonTotalRaiseFunds1 = new javax.swing.JRadioButton();
        jScrollPaneTable = new javax.swing.JScrollPane();
        jTablePoint = new javax.swing.JTable();
        jPanelCongfig = new javax.swing.JPanel();
        jLabelCriticalValue = new javax.swing.JLabel();
        jTextFieldCriticalValue = new javax.swing.JTextField();
        jRadioButtonSuperPurchaseMultiples = new javax.swing.JRadioButton();
        jRadioButtonOfferPrice = new javax.swing.JRadioButton();
        jRadioButtonLuckRate = new javax.swing.JRadioButton();
        jRadioButtonTotalRaiseFunds = new javax.swing.JRadioButton();
        jButtonFilterStart2 = new javax.swing.JButton();
        jPanelCongfig2 = new javax.swing.JPanel();
        jLabelCriticalValue2 = new javax.swing.JLabel();
        jTextFieldCriticalValue2 = new javax.swing.JTextField();
        jRadioButtonSuperPurchaseMultiples2 = new javax.swing.JRadioButton();
        jRadioButtonLuckRate2 = new javax.swing.JRadioButton();
        jRadioButtonTotalRaiseFunds2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCriticalValue3 = new javax.swing.JTextField();
        jPanelCongfig3 = new javax.swing.JPanel();
        jLabelCriticalValue3 = new javax.swing.JLabel();
        jTextFieldCriticalValue4 = new javax.swing.JTextField();
        jRadioButtonSuperPurchaseMultiples3 = new javax.swing.JRadioButton();
        jRadioButtonLuckRate3 = new javax.swing.JRadioButton();
        jRadioButtonTotalRaiseFunds3 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCriticalValue5 = new javax.swing.JTextField();
        jPanelCongfig4 = new javax.swing.JPanel();
        jLabelCriticalValue4 = new javax.swing.JLabel();
        jTextFieldCriticalValue6 = new javax.swing.JTextField();
        jRadioButtonSuperPurchaseMultiples4 = new javax.swing.JRadioButton();
        jRadioButtonLuckRate4 = new javax.swing.JRadioButton();
        jRadioButtonTotalRaiseFunds4 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCriticalValue7 = new javax.swing.JTextField();
        jPanelCongfig5 = new javax.swing.JPanel();
        jRadioButtonSuperPurchaseMultiples5 = new javax.swing.JRadioButton();
        jRadioButtonLuckRate5 = new javax.swing.JRadioButton();
        jRadioButtonTotalRaiseFunds5 = new javax.swing.JRadioButton();
        jPanelCongfig6 = new javax.swing.JPanel();
        jLabelCriticalValue5 = new javax.swing.JLabel();
        jTextFieldCriticalValue8 = new javax.swing.JTextField();
        jRadioButtonSuperPurchaseMultiples6 = new javax.swing.JRadioButton();
        jRadioButtonLuckRate6 = new javax.swing.JRadioButton();
        jRadioButtonTotalRaiseFunds6 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCriticalValue9 = new javax.swing.JTextField();
        jPanelCongfig7 = new javax.swing.JPanel();
        jRadioButtonSuperPurchaseMultiples7 = new javax.swing.JRadioButton();
        jRadioButtonLuckRate7 = new javax.swing.JRadioButton();
        jRadioButtonTotalRaiseFunds7 = new javax.swing.JRadioButton();
        jButtonIpoInfo = new javax.swing.JButton();
        jButtonIpoEva = new javax.swing.JButton();
        jButtonFilterStart = new javax.swing.JButton();
        jButtonFilterStart1 = new javax.swing.JButton();
        jPanelCongfig8 = new javax.swing.JPanel();
        jLabelCriticalValue6 = new javax.swing.JLabel();
        jTextFieldCriticalValue10 = new javax.swing.JTextField();
        jRadioButtonSuperPurchaseMultiples8 = new javax.swing.JRadioButton();
        jRadioButtonLuckRate8 = new javax.swing.JRadioButton();
        jRadioButtonTotalRaiseFunds8 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCriticalValue11 = new javax.swing.JTextField();
        jPanelCongfig9 = new javax.swing.JPanel();
        jLabelCriticalValue7 = new javax.swing.JLabel();
        jTextFieldCriticalValue12 = new javax.swing.JTextField();
        jRadioButtonSuperPurchaseMultiples9 = new javax.swing.JRadioButton();
        jRadioButtonLuckRate9 = new javax.swing.JRadioButton();
        jRadioButtonTotalRaiseFunds9 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCriticalValue13 = new javax.swing.JTextField();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemOpen = new javax.swing.JMenuItem();
        jMenuRun = new javax.swing.JMenu();
        jMenuItemDZH = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("智能证券系统-港股打新");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelCongfig1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "卖出策略", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 12))); // NOI18N
        jPanelCongfig1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup2.add(jRadioButtonSuperPurchaseMultiples1);
        jRadioButtonSuperPurchaseMultiples1.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jRadioButtonSuperPurchaseMultiples1.setText("收盘");
        jPanelCongfig1.add(jRadioButtonSuperPurchaseMultiples1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        buttonGroup2.add(jRadioButtonLuckRate1);
        jRadioButtonLuckRate1.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jRadioButtonLuckRate1.setText("开盘");
        jPanelCongfig1.add(jRadioButtonLuckRate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        buttonGroup2.add(jRadioButtonTotalRaiseFunds1);
        jRadioButtonTotalRaiseFunds1.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jRadioButtonTotalRaiseFunds1.setText("暗盘");
        jPanelCongfig1.add(jRadioButtonTotalRaiseFunds1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jPanelMain.add(jPanelCongfig1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 250, 70));
        jPanelCongfig1.getAccessibleContext().setAccessibleName("统计显示");

        jTablePoint.getTableHeader().setFont(new java.awt.Font("微软雅黑", 0, 12));
        jTablePoint.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTablePoint.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"开盘累计涨幅", null, "收盘累计涨幅", ""},
                {"开盘累计收益", null, "收盘累计收益", null},
                {"开盘加权收益", null, "收盘加权收益", ""},
                {"开盘加限收益", null, "收盘加限收益", null},
                {"开收加限收益", null, "收开加限收益", null},
                {"", null, "", null}
            },
            new String [] {
                "统计指标", "全部交易", "统计指标", "全部交易"
            }
        ));
        jTablePoint.setPreferredSize(new java.awt.Dimension(310, 96));
        jScrollPaneTable.setViewportView(jTablePoint);
        if (jTablePoint.getColumnModel().getColumnCount() > 0) {
            jTablePoint.getColumnModel().getColumn(0).setMinWidth(80);
            jTablePoint.getColumnModel().getColumn(2).setMinWidth(80);
        }

        jPanelMain.add(jScrollPaneTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 500, 126));

        jPanelCongfig.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "定投配置", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 12))); // NOI18N
        jPanelCongfig.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCriticalValue.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabelCriticalValue.setText("临界位：");
        jPanelCongfig.add(jLabelCriticalValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jTextFieldCriticalValue.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTextFieldCriticalValue.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldCriticalValue.setText("1.0");
        jPanelCongfig.add(jTextFieldCriticalValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 68, 110, -1));

        buttonGroup1.add(jRadioButtonSuperPurchaseMultiples);
        jRadioButtonSuperPurchaseMultiples.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jRadioButtonSuperPurchaseMultiples.setText("超购倍数");
        jPanelCongfig.add(jRadioButtonSuperPurchaseMultiples, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        buttonGroup1.add(jRadioButtonOfferPrice);
        jRadioButtonOfferPrice.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jRadioButtonOfferPrice.setText("发行价");
        jPanelCongfig.add(jRadioButtonOfferPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        buttonGroup1.add(jRadioButtonLuckRate);
        jRadioButtonLuckRate.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jRadioButtonLuckRate.setText("中签率");
        jPanelCongfig.add(jRadioButtonLuckRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        buttonGroup1.add(jRadioButtonTotalRaiseFunds);
        jRadioButtonTotalRaiseFunds.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jRadioButtonTotalRaiseFunds.setText("募资总额");
        jPanelCongfig.add(jRadioButtonTotalRaiseFunds, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jButtonFilterStart2.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jButtonFilterStart2.setText("新股分析");
        jButtonFilterStart2.setMargin(new java.awt.Insets(2, 8, 2, 8));
        jButtonFilterStart2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFilterStart2ActionPerformed(evt);
            }
        });
        jPanelCongfig.add(jButtonFilterStart2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 70, 30));

        jPanelMain.add(jPanelCongfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 370, 110));

        jPanelCongfig2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "暗盘涨幅", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 12))); // NOI18N
        jPanelCongfig2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCriticalValue2.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabelCriticalValue2.setText("下位：");
        jPanelCongfig2.add(jLabelCriticalValue2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jTextFieldCriticalValue2.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTextFieldCriticalValue2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldCriticalValue2.setText("0");
        jPanelCongfig2.add(jTextFieldCriticalValue2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 50, -1));

        buttonGroup3.add(jRadioButtonSuperPurchaseMultiples2);
        jRadioButtonSuperPurchaseMultiples2.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jRadioButtonSuperPurchaseMultiples2.setText("区间值");
        jPanelCongfig2.add(jRadioButtonSuperPurchaseMultiples2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        buttonGroup3.add(jRadioButtonLuckRate2);
        jRadioButtonLuckRate2.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jRadioButtonLuckRate2.setText("下值");
        jPanelCongfig2.add(jRadioButtonLuckRate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        buttonGroup3.add(jRadioButtonTotalRaiseFunds2);
        jRadioButtonTotalRaiseFunds2.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jRadioButtonTotalRaiseFunds2.setText("上值");
        jPanelCongfig2.add(jRadioButtonTotalRaiseFunds2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jLabel1.setText("上位：");
        jPanelCongfig2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        jTextFieldCriticalValue3.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTextFieldCriticalValue3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldCriticalValue3.setText("100.0");
        jPanelCongfig2.add(jTextFieldCriticalValue3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 50, -1));

        jPanelMain.add(jPanelCongfig2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 270, 110));

        jPanelCongfig3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "中签率", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 12))); // NOI18N
        jPanelCongfig3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCriticalValue3.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabelCriticalValue3.setText("下位：");
        jPanelCongfig3.add(jLabelCriticalValue3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jTextFieldCriticalValue4.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTextFieldCriticalValue4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldCriticalValue4.setText("0");
        jPanelCongfig3.add(jTextFieldCriticalValue4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 50, -1));

        buttonGroup3.add(jRadioButtonSuperPurchaseMultiples3);
        jRadioButtonSuperPurchaseMultiples3.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jRadioButtonSuperPurchaseMultiples3.setText("区间值");
        jPanelCongfig3.add(jRadioButtonSuperPurchaseMultiples3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        buttonGroup3.add(jRadioButtonLuckRate3);
        jRadioButtonLuckRate3.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jRadioButtonLuckRate3.setSelected(true);
        jRadioButtonLuckRate3.setText("下值");
        jPanelCongfig3.add(jRadioButtonLuckRate3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        buttonGroup3.add(jRadioButtonTotalRaiseFunds3);
        jRadioButtonTotalRaiseFunds3.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jRadioButtonTotalRaiseFunds3.setText("上值");
        jPanelCongfig3.add(jRadioButtonTotalRaiseFunds3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jLabel2.setText("上位：");
        jPanelCongfig3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        jTextFieldCriticalValue5.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTextFieldCriticalValue5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldCriticalValue5.setText("100.0");
        jPanelCongfig3.add(jTextFieldCriticalValue5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 50, -1));

        jPanelMain.add(jPanelCongfig3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 270, 110));

        jPanelCongfig4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "募资总额", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 12))); // NOI18N
        jPanelCongfig4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCriticalValue4.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabelCriticalValue4.setText("下位：");
        jPanelCongfig4.add(jLabelCriticalValue4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jTextFieldCriticalValue6.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTextFieldCriticalValue6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldCriticalValue6.setText("0");
        jPanelCongfig4.add(jTextFieldCriticalValue6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 50, -1));

        buttonGroup3.add(jRadioButtonSuperPurchaseMultiples4);
        jRadioButtonSuperPurchaseMultiples4.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jRadioButtonSuperPurchaseMultiples4.setText("区间值");
        jPanelCongfig4.add(jRadioButtonSuperPurchaseMultiples4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        buttonGroup3.add(jRadioButtonLuckRate4);
        jRadioButtonLuckRate4.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jRadioButtonLuckRate4.setText("下值");
        jPanelCongfig4.add(jRadioButtonLuckRate4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        buttonGroup3.add(jRadioButtonTotalRaiseFunds4);
        jRadioButtonTotalRaiseFunds4.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jRadioButtonTotalRaiseFunds4.setText("上值");
        jPanelCongfig4.add(jRadioButtonTotalRaiseFunds4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jLabel3.setText("上位：");
        jPanelCongfig4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        jTextFieldCriticalValue7.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTextFieldCriticalValue7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldCriticalValue7.setText("100.0");
        jPanelCongfig4.add(jTextFieldCriticalValue7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 50, -1));

        jPanelMain.add(jPanelCongfig4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 270, 110));

        jPanelCongfig5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "统计显示", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 12))); // NOI18N
        jPanelCongfig5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup2.add(jRadioButtonSuperPurchaseMultiples5);
        jRadioButtonSuperPurchaseMultiples5.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jRadioButtonSuperPurchaseMultiples5.setText("加权");
        jPanelCongfig5.add(jRadioButtonSuperPurchaseMultiples5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        buttonGroup2.add(jRadioButtonLuckRate5);
        jRadioButtonLuckRate5.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jRadioButtonLuckRate5.setSelected(true);
        jRadioButtonLuckRate5.setText("全部");
        jPanelCongfig5.add(jRadioButtonLuckRate5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        buttonGroup2.add(jRadioButtonTotalRaiseFunds5);
        jRadioButtonTotalRaiseFunds5.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jRadioButtonTotalRaiseFunds5.setText("累加");
        jPanelCongfig5.add(jRadioButtonTotalRaiseFunds5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jPanelMain.add(jPanelCongfig5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 250, 70));

        jPanelCongfig6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "超购倍数", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 12))); // NOI18N
        jPanelCongfig6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCriticalValue5.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabelCriticalValue5.setText("下位：");
        jPanelCongfig6.add(jLabelCriticalValue5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jTextFieldCriticalValue8.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTextFieldCriticalValue8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldCriticalValue8.setText("0");
        jPanelCongfig6.add(jTextFieldCriticalValue8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 50, -1));

        buttonGroup3.add(jRadioButtonSuperPurchaseMultiples6);
        jRadioButtonSuperPurchaseMultiples6.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jRadioButtonSuperPurchaseMultiples6.setText("区间值");
        jPanelCongfig6.add(jRadioButtonSuperPurchaseMultiples6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        buttonGroup3.add(jRadioButtonLuckRate6);
        jRadioButtonLuckRate6.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jRadioButtonLuckRate6.setText("下值");
        jPanelCongfig6.add(jRadioButtonLuckRate6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        buttonGroup3.add(jRadioButtonTotalRaiseFunds6);
        jRadioButtonTotalRaiseFunds6.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jRadioButtonTotalRaiseFunds6.setText("上值");
        jPanelCongfig6.add(jRadioButtonTotalRaiseFunds6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jLabel4.setText("上位：");
        jPanelCongfig6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        jTextFieldCriticalValue9.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTextFieldCriticalValue9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldCriticalValue9.setText("100.0");
        jPanelCongfig6.add(jTextFieldCriticalValue9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 50, -1));

        jPanelMain.add(jPanelCongfig6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 270, 110));

        jPanelCongfig7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "板块", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 12))); // NOI18N
        jPanelCongfig7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup2.add(jRadioButtonSuperPurchaseMultiples7);
        jRadioButtonSuperPurchaseMultiples7.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jRadioButtonSuperPurchaseMultiples7.setText("主板");
        jPanelCongfig7.add(jRadioButtonSuperPurchaseMultiples7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        buttonGroup2.add(jRadioButtonLuckRate7);
        jRadioButtonLuckRate7.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jRadioButtonLuckRate7.setText("全部");
        jPanelCongfig7.add(jRadioButtonLuckRate7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        buttonGroup2.add(jRadioButtonTotalRaiseFunds7);
        jRadioButtonTotalRaiseFunds7.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jRadioButtonTotalRaiseFunds7.setText("创业板");
        jPanelCongfig7.add(jRadioButtonTotalRaiseFunds7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jPanelMain.add(jPanelCongfig7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 250, 70));

        jButtonIpoInfo.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jButtonIpoInfo.setText("新股信息");
        jButtonIpoInfo.setMargin(new java.awt.Insets(2, 8, 2, 8));
        jButtonIpoInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIpoInfoActionPerformed(evt);
            }
        });
        jPanelMain.add(jButtonIpoInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 150, -1, 30));

        jButtonIpoEva.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jButtonIpoEva.setText("投资评测");
        jButtonIpoEva.setMargin(new java.awt.Insets(2, 8, 2, 8));
        jButtonIpoEva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIpoEvaActionPerformed(evt);
            }
        });
        jPanelMain.add(jButtonIpoEva, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 190, -1, 30));

        jButtonFilterStart.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jButtonFilterStart.setText("统计分析");
        jButtonFilterStart.setMargin(new java.awt.Insets(2, 8, 2, 8));
        jButtonFilterStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFilterStartActionPerformed(evt);
            }
        });
        jPanelMain.add(jButtonFilterStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 230, 70, 30));

        jButtonFilterStart1.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jButtonFilterStart1.setText("暗盘分析");
        jButtonFilterStart1.setMargin(new java.awt.Insets(2, 8, 2, 8));
        jButtonFilterStart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFilterStart1ActionPerformed(evt);
            }
        });
        jPanelMain.add(jButtonFilterStart1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 270, 70, 30));

        jPanelCongfig8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "发行价", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 12))); // NOI18N
        jPanelCongfig8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCriticalValue6.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabelCriticalValue6.setText("下位：");
        jPanelCongfig8.add(jLabelCriticalValue6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jTextFieldCriticalValue10.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTextFieldCriticalValue10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldCriticalValue10.setText("0");
        jPanelCongfig8.add(jTextFieldCriticalValue10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 50, -1));

        buttonGroup3.add(jRadioButtonSuperPurchaseMultiples8);
        jRadioButtonSuperPurchaseMultiples8.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jRadioButtonSuperPurchaseMultiples8.setText("区间值");
        jPanelCongfig8.add(jRadioButtonSuperPurchaseMultiples8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        buttonGroup3.add(jRadioButtonLuckRate8);
        jRadioButtonLuckRate8.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jRadioButtonLuckRate8.setText("下值");
        jPanelCongfig8.add(jRadioButtonLuckRate8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        buttonGroup3.add(jRadioButtonTotalRaiseFunds8);
        jRadioButtonTotalRaiseFunds8.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jRadioButtonTotalRaiseFunds8.setText("上值");
        jPanelCongfig8.add(jRadioButtonTotalRaiseFunds8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jLabel5.setText("上位：");
        jPanelCongfig8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        jTextFieldCriticalValue11.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTextFieldCriticalValue11.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldCriticalValue11.setText("100.0");
        jPanelCongfig8.add(jTextFieldCriticalValue11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 50, -1));

        jPanelMain.add(jPanelCongfig8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 270, 110));

        jPanelCongfig9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "绿鞋/公开", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 12))); // NOI18N
        jPanelCongfig9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCriticalValue7.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabelCriticalValue7.setText("下位：");
        jPanelCongfig9.add(jLabelCriticalValue7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jTextFieldCriticalValue12.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTextFieldCriticalValue12.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldCriticalValue12.setText("0");
        jPanelCongfig9.add(jTextFieldCriticalValue12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 50, -1));

        buttonGroup3.add(jRadioButtonSuperPurchaseMultiples9);
        jRadioButtonSuperPurchaseMultiples9.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jRadioButtonSuperPurchaseMultiples9.setText("区间值");
        jPanelCongfig9.add(jRadioButtonSuperPurchaseMultiples9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        buttonGroup3.add(jRadioButtonLuckRate9);
        jRadioButtonLuckRate9.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jRadioButtonLuckRate9.setText("下值");
        jPanelCongfig9.add(jRadioButtonLuckRate9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        buttonGroup3.add(jRadioButtonTotalRaiseFunds9);
        jRadioButtonTotalRaiseFunds9.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jRadioButtonTotalRaiseFunds9.setText("上值");
        jPanelCongfig9.add(jRadioButtonTotalRaiseFunds9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jLabel6.setText("上位：");
        jPanelCongfig9.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        jTextFieldCriticalValue13.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTextFieldCriticalValue13.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldCriticalValue13.setText("100.0");
        jPanelCongfig9.add(jTextFieldCriticalValue13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 50, -1));

        jPanelMain.add(jPanelCongfig9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 270, 110));

        getContentPane().add(jPanelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 520));

        jMenuFile.setText("文件");

        jMenuItemOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemOpen.setText("打开...");
        jMenuItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpenActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemOpen);

        jMenuBar.add(jMenuFile);

        jMenuRun.setText("运行");

        jMenuItemDZH.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemDZH.setText("大智慧");
        jMenuItemDZH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDZHActionPerformed(evt);
            }
        });
        jMenuRun.add(jMenuItemDZH);

        jMenuBar.add(jMenuRun);

        jMenuHelp.setText("帮助");

        jMenuItemAbout.setText("关于");
        jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItemAbout);

        jMenuBar.add(jMenuHelp);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpenActionPerformed
    }//GEN-LAST:event_jMenuItemOpenActionPerformed

    private void jMenuItemDZHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDZHActionPerformed
        runExeFile("C:\\dzh365\\dzh2.exe");
    }//GEN-LAST:event_jMenuItemDZHActionPerformed

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
        JOptionPane.showMessageDialog(new JFrame(), "智能证券系统-港股打新 V19.10\n版权所有(C) 张向荣(Aioros Zhang)");
    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    private void jButtonIpoInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIpoInfoActionPerformed
        importData();
        IpoTable ipoTable = new IpoTable(this, false, ipoInfoList);
    }//GEN-LAST:event_jButtonIpoInfoActionPerformed

    private void jButtonIpoEvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIpoEvaActionPerformed
        int type = 1;
        if (jRadioButtonLuckRate.isSelected()) {
            type = 1;
        } else if (jRadioButtonSuperPurchaseMultiples.isSelected()) {
            type = 2;
        } else if (jRadioButtonTotalRaiseFunds.isSelected()) {
            type = 3;
        } else {
            type = 4;
        }
        float critPoint = Float.parseFloat(jTextFieldCriticalValue.getText());
        strategy = new Strategy(ipoInfoList);

        SystemReport sr = updateSystemReport(strategy, type, critPoint);
        updateTable(sr);

        evaluated = true;
    }//GEN-LAST:event_jButtonIpoEvaActionPerformed

    private void jButtonFilterStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFilterStartActionPerformed
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        SystemReport sr;
        ArrayList<SystemReport> srList = new ArrayList<>();

        strategy = new Strategy(ipoInfoList);
        float oldOWeightRestictEarn = 0;
        if (jRadioButtonLuckRate.isSelected()) {
            for (int i = 1; i <= 100; i++) {
                sr = updateSimpleReport(strategy, 1, (float) i);
                if (sr.OWeightEarnRestict != oldOWeightRestictEarn) {
                    oldOWeightRestictEarn = sr.OWeightEarnRestict;
                    srList.add(sr);
                }
            }
        } else if (jRadioButtonSuperPurchaseMultiples.isSelected()) {
            for (int i = 1; i < 1000; i++) {
                sr = updateSimpleReport(strategy, 2, (float) i);
                if (sr.OWeightEarnRestict != oldOWeightRestictEarn) {
                    oldOWeightRestictEarn = sr.OWeightEarnRestict;
                    srList.add(sr);
                }
            }
        } else if (jRadioButtonTotalRaiseFunds.isSelected()) {
            for (int i = 1; i <= 1000; i++) {
                sr = updateSimpleReport(strategy, 3, (float) i / 10);
                if (sr.OWeightEarnRestict != oldOWeightRestictEarn) {
                    oldOWeightRestictEarn = sr.OWeightEarnRestict;
                    srList.add(sr);
                }
            }
        } else {
            for (int i = 1; i < 1000; i++) {
                sr = updateSimpleReport(strategy, 4, (float) i / 10);
                if (sr.OWeightEarnRestict != oldOWeightRestictEarn) {
                    oldOWeightRestictEarn = sr.OWeightEarnRestict;
                    srList.add(sr);
                }
            }
        }

        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));

        //Collections.sort(srList, (SystemReport arg0, SystemReport arg1) -> new Float(arg1.OWeightEarnRestict).compareTo(arg0.OWeightEarnRestict));
        RankTable rankTable = new RankTable(this, false, this, srList);
    }//GEN-LAST:event_jButtonFilterStartActionPerformed

    private void jButtonFilterStart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFilterStart1ActionPerformed
        int items = ipoInfoList.size();
        int t_num = 0;
        int num = 0;
        float money = 0;
        float level = (float) 0.4;
        for (int bg = 30; bg < 31; bg++) {
            System.out.println("bg:" + bg);
            for (int f = 43; f <= 43; f++) {
                level = (float) f / 100;
                num = 0;
                money = 0;
                t_num = 0;
                for (int i = 0; i < items; i++) {
                    if (ipoInfoList.get(i).grayGain > bg) {
                        t_num++;
                        float bp = ipoInfoList.get(i).grayPrice;
                        float op = ipoInfoList.get(i).openPrice;
                        float hp = ipoInfoList.get(i).highPrice;
                        float lp = ipoInfoList.get(i).lowPrice;
                        float cp = ipoInfoList.get(i).closePrice;
                        float hf = ipoInfoList.get(i).handFund / ipoInfoList.get(i).offerPrice;
                        String openGain = String.format("%.1f", 100 * (op / bp - 1));
                        String highGain = String.format("%.1f", 100 * (hp / bp - 1));
                        String lowGain = String.format("%.1f", 100 * (lp / bp - 1));
                        String closeGain = String.format("%.1f", 100 * (cp / bp - 1));
                        //System.out.println("openGain: " + openGain + "\thighGain: " + highGain  + "\tcloseGain: " + closeGain + "\t" + ipoInfoList.get(i).stockName);
                        float earn = 0;
                        if (op / bp - 1 >= level) {
                            num++;
                            earn = hf * (op - bp);
                            //System.out.println("openGain: " + openGain + "\thighGain: " + highGain + "\tcloseGain: " + closeGain + "\tearn: " + earn + "\t" + ipoInfoList.get(i).blackGain + "\t" + ipoInfoList.get(i).stockName);
                        } else if (hp / bp - 1 >= level) {
                            num++;
                            earn = hf * bp * level;
                            //System.out.println("openGain: " + openGain + "\thighGain: " + highGain + "\tcloseGain: " + closeGain + "\t" + ipoInfoList.get(i).blackGain + "\t" + ipoInfoList.get(i).stockName);
                        } else {
                            earn = hf * (cp - bp);
                            //System.out.println("openGain: " + openGain + "\thighGain: " + highGain + "\tcloseGain: " + closeGain + "\t" + ipoInfoList.get(i).blackGain + "\t" + ipoInfoList.get(i).stockName);
                        }
                        System.out.println("openGain: " + openGain + "\thighGain: " + highGain + "\tcloseGain: " + closeGain + "\tearn: " + earn + "\tblackGain: " + ipoInfoList.get(i).grayGain + "\t" + ipoInfoList.get(i).stockName);
                        money += earn;
                    }
                }
                System.out.println("t_num: " + t_num + "\tnum: " + num + "\tpercent: " + (float) num / t_num + "\tmoney: " + money);
            }
        }
    }//GEN-LAST:event_jButtonFilterStart1ActionPerformed

    private void jButtonFilterStart2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFilterStart2ActionPerformed
        int items = ipoInfoList.size();
        int t_num = 0;
        int num = 0;
        float money = 0;
        float level = (float) 0.4;

        for (int f = 250; f <= 250; f++) {
            level = (float) f / 100;
            num = 0;
            money = 0;
            t_num = 0;
            for (int i = 0; i < items; i++) {
                t_num++;
                float ip = ipoInfoList.get(i).offerPrice;
                float op = ipoInfoList.get(i).openPrice;
                float hp = ipoInfoList.get(i).highPrice;
                float lp = ipoInfoList.get(i).lowPrice;
                float cp = ipoInfoList.get(i).closePrice;
                float hf = ipoInfoList.get(i).handFund / ipoInfoList.get(i).offerPrice;
                float lr = ipoInfoList.get(i).luckyRate / 100;
                float rf = ipoInfoList.get(i).totalRaiseFunds;
                String openGain = String.format("%.1f", 100 * (op / ip - 1));
                String highGain = String.format("%.1f", 100 * (hp / ip - 1));
                String lowGain = String.format("%.1f", 100 * (lp / ip - 1));
                String closeGain = String.format("%.1f", 100 * (cp / ip - 1));
                //System.out.println("openGain: " + openGain + "\thighGain: " + highGain  + "\tcloseGain: " + closeGain + "\t" + ipoInfoList.get(i).stockName);
                if ((op / ip - 1 >= level) || (rf < 1.4)) {
                    num++;
                    money += hf * (op - ip) * lr;
                    //System.out.println("openGain: " + openGain + "\thighGain: " + highGain  + "\tcloseGain: " + closeGain + "\t" + ipoInfoList.get(i).blackGain + "\t" + ipoInfoList.get(i).stockName);
                } else if (hp / ip - 1 >= level) {
                    num++;
                    money += hf * ip * level * lr;
                    System.out.println("openGain: " + openGain + "\thighGain: " + highGain + "\tcloseGain: " + closeGain + "\t" + ipoInfoList.get(i).grayGain + "\t" + ipoInfoList.get(i).stockName);
                } else {
                    money += hf * (cp - ip) * lr;
                    //System.out.println("openGain: " + openGain + "\thighGain: " + highGain  + "\tcloseGain: " + closeGain + "\t" + ipoInfoList.get(i).blackGain + "\t" + ipoInfoList.get(i).stockName);
                }
            }
            System.out.println("level: " + f + "\tnum: " + num + "\tpercent: " + (float) num / t_num + "\tmoney: " + money);

        }
    }//GEN-LAST:event_jButtonFilterStart2ActionPerformed

    /**
     ********************* Start of User-defined function ********************
     */
    protected void importData() {
        try {
            File file = new File(fileIn);
            InputStreamReader isr = new InputStreamReader(new FileInputStream(file), "gbk");
            BufferedReader br = new BufferedReader(isr);
            String[] words = br.readLine().split("\t+");
            column = words.length;
            ipoInfoList = new ArrayList<>();
            String line;
            while ((line = br.readLine()) != null) {
                words = line.split("\t+");
                IpoInfo ipoInfo = new IpoInfo(words[0], words[1]);
                ipoInfo.marketPlate = words[2];
                ipoInfo.offerDate = words[3];
                ipoInfo.inquiryRange = words[4];
                ipoInfo.handFund = Integer.parseInt(words[5]);
                ipoInfo.luckyRate = Float.parseFloat(words[6].substring(0, words[6].length() - 1));
                ipoInfo.offerPrice = Float.parseFloat(words[7]);
                ipoInfo.offerPE = words[8];
                ipoInfo.greenShoeRatio = words[9].equals("-") ? 0 : Float.parseFloat(words[9].substring(0, words[9].length() - 1));;
                ipoInfo.comparableCompany = words[10];
                ipoInfo.superPurchaseMultiples = Float.parseFloat(words[11]);
                ipoInfo.totalRaiseFunds = Float.parseFloat(words[12]);
                ipoInfo.grayGain = Float.parseFloat(words[13].substring(0, words[13].length() - 1));
                ipoInfo.closeGain = Float.parseFloat(words[14].substring(0, words[14].length() - 1));
                ipoInfo.openPrice = Float.parseFloat(words[15]);
                ipoInfo.highPrice = Float.parseFloat(words[16]);
                ipoInfo.lowPrice = Float.parseFloat(words[17]);
                ipoInfo.closePrice = Float.parseFloat(words[18]);
                ipoInfo.underwriter = words[19];

                ipoInfo.openGain = 100 * (ipoInfo.openPrice - ipoInfo.offerPrice) / ipoInfo.offerPrice;
                ipoInfo.grayPrice = ipoInfo.offerPrice * (1 + ipoInfo.grayGain / 100);
                ipoInfoList.add(ipoInfo);
            }
            stocks = ipoInfoList.size();
            br.close();
            isr.close();
        } catch (IOException | NumberFormatException e) {
            e.printStackTrace();
        }

        evaluated = false;
    }

    public void investParaEva(String para) {
        String[] paras = para.replaceAll(" ", "").split(",");
        jTextFieldCriticalValue.setText(paras[2]);

        jButtonIpoEva.doClick();
    }

    public void getInvestMode() {
    }

    protected SystemReport updateSystemReport(Strategy stg, int type, float cp) {
        SystemReport sr = new SystemReport(cp);

        sr.OTotalGain = stg.getOTotalGain();
        sr.CTotalGain = stg.getCTotalGain();
        sr.OTotalEarn = stg.getOTotalEarn();
        sr.CTotalEarn = stg.getCTotalEarn();
        sr.OWeightEarn = stg.getOWeightEarn();
        sr.CWeightEarn = stg.getCWeightEarn();
        sr.OWeightEarnRestict = stg.getOWeightEarnRestict(type, cp);
        sr.CWeightEarnRestict = stg.getCWeightEarnRestict(type, cp);
        sr.OCWeightEarnRestict = stg.getOCWeightEarnRestict(type, cp);
        sr.COWeightEarnRestict = stg.getCOWeightEarnRestict(type, cp);
        return sr;
    }

    protected SystemReport updateSimpleReport(Strategy stg, int type, float cp) {
        SystemReport sr = new SystemReport(cp);

        sr.OWeightEarnRestict = strategy.getOWeightEarnRestict(type, cp);
        sr.CWeightEarnRestict = strategy.getCWeightEarnRestict(type, cp);
        sr.OCWeightEarnRestict = strategy.getOCWeightEarnRestict(type, cp);
        sr.COWeightEarnRestict = strategy.getCOWeightEarnRestict(type, cp);
        return sr;
    }

    protected void updateTable(SystemReport sr) {
        jTablePoint.setValueAt("开盘累计涨幅", 0, 0);
        jTablePoint.setValueAt(sr.OTotalGain + "%", 0, 1);
        jTablePoint.setValueAt("收盘累计涨幅", 0, 2);
        jTablePoint.setValueAt(sr.CTotalGain + "%", 0, 3);
        jTablePoint.setValueAt("开盘累计收益", 1, 0);
        jTablePoint.setValueAt(sr.OTotalEarn + "元", 1, 1);
        jTablePoint.setValueAt("收盘累计收益", 1, 2);
        jTablePoint.setValueAt(sr.CTotalEarn + "元", 1, 3);
        jTablePoint.setValueAt("开盘加权收益", 2, 0);
        jTablePoint.setValueAt(sr.OWeightEarn + "元", 2, 1);
        jTablePoint.setValueAt("收盘加权收益", 2, 2);
        jTablePoint.setValueAt(sr.CWeightEarn + "元", 2, 3);
        jTablePoint.setValueAt("开盘加限收益", 3, 0);
        jTablePoint.setValueAt(sr.OWeightEarnRestict + "元", 3, 1);
        jTablePoint.setValueAt("收盘加限收益", 3, 2);
        jTablePoint.setValueAt(sr.CWeightEarnRestict + "元", 3, 3);
        jTablePoint.setValueAt("开收加限收益", 4, 0);
        jTablePoint.setValueAt(sr.OCWeightEarnRestict + "元", 4, 1);
        jTablePoint.setValueAt("收开加限收益", 4, 2);
        jTablePoint.setValueAt(sr.COWeightEarnRestict + "元", 4, 3);
    }

    public void msgLogger(String str) {
        //jTextAreaMain.append(str + System.getProperty("line.separator"));
    }

    public void fileLogger(String str) {
        if (fileWriter != null) {
            try {
                fileWriter.write(str + System.getProperty("line.separator"));
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }

    public void runExeFile(String file) {
        try {
            Runtime rt = Runtime.getRuntime();
            File exeFile = new File(file);
            if (exeFile.exists()) {
                String cmd = "cmd.exe /c " + file;
                rt.exec(cmd);
            } else {
                JOptionPane.showMessageDialog(new JFrame(), "请先安装相关软件到根目录！");
            }
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    private String fileIn = "data\\港股新股.txt";
    public FileWriter fileWriter;

    public String stockName = "W上证指数";
    public String stockCode = "000001";
    public int column = 0;
    public int stocks = 0;

    public int sIdx = -1;
    public int eIdx = 0;
    public int investDays = 0;
    public double testYears = 0;
    public double investCoef = 1;

    public Strategy strategy;
    public boolean evaluated = false;
    //public RankTable rankTable;
    public String investPara;
    public ArrayList<CheckData> chkDataList;

    ArrayList<IpoInfo> ipoInfoList;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButtonFilterStart;
    private javax.swing.JButton jButtonFilterStart1;
    private javax.swing.JButton jButtonFilterStart2;
    private javax.swing.JButton jButtonIpoEva;
    private javax.swing.JButton jButtonIpoInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelCriticalValue;
    private javax.swing.JLabel jLabelCriticalValue2;
    private javax.swing.JLabel jLabelCriticalValue3;
    private javax.swing.JLabel jLabelCriticalValue4;
    private javax.swing.JLabel jLabelCriticalValue5;
    private javax.swing.JLabel jLabelCriticalValue6;
    private javax.swing.JLabel jLabelCriticalValue7;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemDZH;
    private javax.swing.JMenuItem jMenuItemOpen;
    private javax.swing.JMenu jMenuRun;
    private javax.swing.JPanel jPanelCongfig;
    private javax.swing.JPanel jPanelCongfig1;
    private javax.swing.JPanel jPanelCongfig2;
    private javax.swing.JPanel jPanelCongfig3;
    private javax.swing.JPanel jPanelCongfig4;
    private javax.swing.JPanel jPanelCongfig5;
    private javax.swing.JPanel jPanelCongfig6;
    private javax.swing.JPanel jPanelCongfig7;
    private javax.swing.JPanel jPanelCongfig8;
    private javax.swing.JPanel jPanelCongfig9;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JRadioButton jRadioButtonLuckRate;
    private javax.swing.JRadioButton jRadioButtonLuckRate1;
    private javax.swing.JRadioButton jRadioButtonLuckRate2;
    private javax.swing.JRadioButton jRadioButtonLuckRate3;
    private javax.swing.JRadioButton jRadioButtonLuckRate4;
    private javax.swing.JRadioButton jRadioButtonLuckRate5;
    private javax.swing.JRadioButton jRadioButtonLuckRate6;
    private javax.swing.JRadioButton jRadioButtonLuckRate7;
    private javax.swing.JRadioButton jRadioButtonLuckRate8;
    private javax.swing.JRadioButton jRadioButtonLuckRate9;
    private javax.swing.JRadioButton jRadioButtonOfferPrice;
    private javax.swing.JRadioButton jRadioButtonSuperPurchaseMultiples;
    private javax.swing.JRadioButton jRadioButtonSuperPurchaseMultiples1;
    private javax.swing.JRadioButton jRadioButtonSuperPurchaseMultiples2;
    private javax.swing.JRadioButton jRadioButtonSuperPurchaseMultiples3;
    private javax.swing.JRadioButton jRadioButtonSuperPurchaseMultiples4;
    private javax.swing.JRadioButton jRadioButtonSuperPurchaseMultiples5;
    private javax.swing.JRadioButton jRadioButtonSuperPurchaseMultiples6;
    private javax.swing.JRadioButton jRadioButtonSuperPurchaseMultiples7;
    private javax.swing.JRadioButton jRadioButtonSuperPurchaseMultiples8;
    private javax.swing.JRadioButton jRadioButtonSuperPurchaseMultiples9;
    private javax.swing.JRadioButton jRadioButtonTotalRaiseFunds;
    private javax.swing.JRadioButton jRadioButtonTotalRaiseFunds1;
    private javax.swing.JRadioButton jRadioButtonTotalRaiseFunds2;
    private javax.swing.JRadioButton jRadioButtonTotalRaiseFunds3;
    private javax.swing.JRadioButton jRadioButtonTotalRaiseFunds4;
    private javax.swing.JRadioButton jRadioButtonTotalRaiseFunds5;
    private javax.swing.JRadioButton jRadioButtonTotalRaiseFunds6;
    private javax.swing.JRadioButton jRadioButtonTotalRaiseFunds7;
    private javax.swing.JRadioButton jRadioButtonTotalRaiseFunds8;
    private javax.swing.JRadioButton jRadioButtonTotalRaiseFunds9;
    private javax.swing.JScrollPane jScrollPaneTable;
    private javax.swing.JTable jTablePoint;
    private javax.swing.JTextField jTextFieldCriticalValue;
    private javax.swing.JTextField jTextFieldCriticalValue10;
    private javax.swing.JTextField jTextFieldCriticalValue11;
    private javax.swing.JTextField jTextFieldCriticalValue12;
    private javax.swing.JTextField jTextFieldCriticalValue13;
    private javax.swing.JTextField jTextFieldCriticalValue2;
    private javax.swing.JTextField jTextFieldCriticalValue3;
    private javax.swing.JTextField jTextFieldCriticalValue4;
    private javax.swing.JTextField jTextFieldCriticalValue5;
    private javax.swing.JTextField jTextFieldCriticalValue6;
    private javax.swing.JTextField jTextFieldCriticalValue7;
    private javax.swing.JTextField jTextFieldCriticalValue8;
    private javax.swing.JTextField jTextFieldCriticalValue9;
    // End of variables declaration//GEN-END:variables
}
