/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Stagging;

import java.awt.Cursor;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author zhangxr
 */
public class MainView extends javax.swing.JFrame {

    public class CheckData {

        public CheckData(String m, String para) {
            mode = m;
            parameter = para;
        }
        public String mode;
        public String parameter;
        public String status;
        public int days;
        public double key;
        public double percent;
        public String amount;
    }

    /**
     * Creates new form StockerView
     */
    public MainView() {
        initComponents();
        setLocationRelativeTo(null);
        final URL filename = getClass().getResource("/resource/Livermore3.jpg");
        if (filename != null) {
            setIconImage(new ImageIcon(filename, "Icon").getImage());
        }
        importData();
        getUnderwriter();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelMain = new javax.swing.JPanel();
        jPanelDebug = new javax.swing.JPanel();
        jComboBox10 = new javax.swing.JComboBox<>();
        jButtonBigDataAnalysis = new javax.swing.JButton();
        jButtonGrayAnalysis = new javax.swing.JButton();
        jButtonFilterStart2 = new javax.swing.JButton();
        jPanelConf1 = new javax.swing.JPanel();
        jComboBoxS1 = new javax.swing.JComboBox<>();
        jPanelConf2 = new javax.swing.JPanel();
        jComboBoxS2 = new javax.swing.JComboBox<>();
        jPanelConf3 = new javax.swing.JPanel();
        jComboBoxS3 = new javax.swing.JComboBox<>();
        jButtonIpoInfo = new javax.swing.JButton();
        jButtonIpoEva = new javax.swing.JButton();
        jPanelConfig0 = new javax.swing.JPanel();
        jComboBox0 = new javax.swing.JComboBox<>();
        jLabelL0 = new javax.swing.JLabel();
        jTextFieldL0 = new javax.swing.JTextField();
        jLabelH0 = new javax.swing.JLabel();
        jTextFieldH0 = new javax.swing.JTextField();
        jPanelConfig1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabelL1 = new javax.swing.JLabel();
        jTextFieldL1 = new javax.swing.JTextField();
        jLabelH1 = new javax.swing.JLabel();
        jTextFieldH1 = new javax.swing.JTextField();
        jPanelConfig2 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabelL2 = new javax.swing.JLabel();
        jTextFieldL2 = new javax.swing.JTextField();
        jLabelH2 = new javax.swing.JLabel();
        jTextFieldH2 = new javax.swing.JTextField();
        jPanelConfig3 = new javax.swing.JPanel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabelL3 = new javax.swing.JLabel();
        jTextFieldL3 = new javax.swing.JTextField();
        jLabelH3 = new javax.swing.JLabel();
        jTextFieldH3 = new javax.swing.JTextField();
        jPanelConfig4 = new javax.swing.JPanel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabelL4 = new javax.swing.JLabel();
        jTextFieldL4 = new javax.swing.JTextField();
        jLabelH4 = new javax.swing.JLabel();
        jTextFieldH4 = new javax.swing.JTextField();
        jPanelConfig5 = new javax.swing.JPanel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabelL5 = new javax.swing.JLabel();
        jTextFieldL5 = new javax.swing.JTextField();
        jLabelH5 = new javax.swing.JLabel();
        jTextFieldH5 = new javax.swing.JTextField();
        jPanelConfig6 = new javax.swing.JPanel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabelL6 = new javax.swing.JLabel();
        jTextFieldL6 = new javax.swing.JTextField();
        jLabelH6 = new javax.swing.JLabel();
        jTextFieldH6 = new javax.swing.JTextField();
        jButtonUnderwriter = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemOpen = new javax.swing.JMenuItem();
        jMenuRun = new javax.swing.JMenu();
        jMenuItemDZH = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("智能证券系统-港股打新");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelDebug.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "调试区域", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 12))); // NOI18N
        jPanelDebug.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox10.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "一手资金", "中签率", "发行价", "绿鞋/公开", "超购倍数", "募资总额" }));
        jComboBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox10ActionPerformed(evt);
            }
        });
        jPanelDebug.add(jComboBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jButtonBigDataAnalysis.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jButtonBigDataAnalysis.setText("大数分析");
        jButtonBigDataAnalysis.setMargin(new java.awt.Insets(2, 8, 2, 8));
        jButtonBigDataAnalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBigDataAnalysisActionPerformed(evt);
            }
        });
        jPanelDebug.add(jButtonBigDataAnalysis, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 70, 30));

        jButtonGrayAnalysis.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jButtonGrayAnalysis.setText("暗盘分析");
        jButtonGrayAnalysis.setMargin(new java.awt.Insets(2, 8, 2, 8));
        jButtonGrayAnalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGrayAnalysisActionPerformed(evt);
            }
        });
        jPanelDebug.add(jButtonGrayAnalysis, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 70, 30));

        jButtonFilterStart2.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jButtonFilterStart2.setText("新股分析");
        jButtonFilterStart2.setMargin(new java.awt.Insets(2, 8, 2, 8));
        jButtonFilterStart2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFilterStart2ActionPerformed(evt);
            }
        });
        jPanelDebug.add(jButtonFilterStart2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 70, 30));

        jPanelMain.add(jPanelDebug, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 340, 360));

        jPanelConf1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "板块", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 12))); // NOI18N
        jPanelConf1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBoxS1.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jComboBoxS1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "全部", "主板", "创业板" }));
        jComboBoxS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxS1ActionPerformed(evt);
            }
        });
        jPanelConf1.add(jComboBoxS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 25, 70, -1));

        jPanelMain.add(jPanelConf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 70));

        jPanelConf2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "统计时间", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 12))); // NOI18N
        jPanelConf2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBoxS2.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jComboBoxS2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "全部", "近三月", "近半年", "近一年", "近两年", "2021", "2020", "2019", "2018", "2017" }));
        jComboBoxS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxS2ActionPerformed(evt);
            }
        });
        jPanelConf2.add(jComboBoxS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 25, 70, -1));

        jPanelMain.add(jPanelConf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 10, 110, 70));

        jPanelConf3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "卖出策略", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 12))); // NOI18N
        jPanelConf3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBoxS3.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jComboBoxS3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "暗盘", "开盘", "收盘" }));
        jComboBoxS3.setSelectedIndex(2);
        jComboBoxS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxS3ActionPerformed(evt);
            }
        });
        jPanelConf3.add(jComboBoxS3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 25, 70, -1));

        jPanelMain.add(jPanelConf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 110, 70));
        jPanelConf3.getAccessibleContext().setAccessibleName("统计显示");

        jButtonIpoInfo.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jButtonIpoInfo.setText("新股信息");
        jButtonIpoInfo.setMargin(new java.awt.Insets(2, 8, 2, 8));
        jButtonIpoInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIpoInfoActionPerformed(evt);
            }
        });
        jPanelMain.add(jButtonIpoInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, 30));

        jButtonIpoEva.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jButtonIpoEva.setText("投资评测");
        jButtonIpoEva.setMargin(new java.awt.Insets(2, 8, 2, 8));
        jButtonIpoEva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIpoEvaActionPerformed(evt);
            }
        });
        jPanelMain.add(jButtonIpoEva, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, -1, 30));

        jPanelConfig0.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "中签率", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 12))); // NOI18N
        jPanelConfig0.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox0.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jComboBox0.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "全部", "区间下值", "区间中值", "区间上值" }));
        jComboBox0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox0ActionPerformed(evt);
            }
        });
        jPanelConfig0.add(jComboBox0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 25, -1, -1));

        jLabelL0.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabelL0.setText("下值：");
        jPanelConfig0.add(jLabelL0, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 28, -1, -1));

        jTextFieldL0.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTextFieldL0.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldL0.setText("0");
        jPanelConfig0.add(jTextFieldL0, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 25, 50, -1));

        jLabelH0.setText("上值：");
        jPanelConfig0.add(jLabelH0, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 28, -1, -1));

        jTextFieldH0.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTextFieldH0.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldH0.setText("100.0");
        jPanelConfig0.add(jTextFieldH0, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 25, 50, -1));

        jPanelMain.add(jPanelConfig0, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 340, 70));

        jPanelConfig1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "发行价", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 12))); // NOI18N
        jPanelConfig1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "全部", "区间下值", "区间中值", "区间上值" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanelConfig1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 25, -1, -1));

        jLabelL1.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabelL1.setText("下值：");
        jPanelConfig1.add(jLabelL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 28, -1, -1));

        jTextFieldL1.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTextFieldL1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldL1.setText("0");
        jPanelConfig1.add(jTextFieldL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 25, 50, -1));

        jLabelH1.setText("上值：");
        jPanelConfig1.add(jLabelH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 28, -1, -1));

        jTextFieldH1.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTextFieldH1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldH1.setText("100.0");
        jPanelConfig1.add(jTextFieldH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 25, 50, -1));

        jPanelMain.add(jPanelConfig1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 340, 70));

        jPanelConfig2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "绿鞋/公开", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 12))); // NOI18N
        jPanelConfig2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox2.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "全部", "区间下值", "区间中值", "区间上值" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanelConfig2.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 25, -1, -1));

        jLabelL2.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabelL2.setText("下值：");
        jPanelConfig2.add(jLabelL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 28, -1, -1));

        jTextFieldL2.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTextFieldL2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldL2.setText("0");
        jPanelConfig2.add(jTextFieldL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 25, 50, -1));

        jLabelH2.setText("上值：");
        jPanelConfig2.add(jLabelH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 28, -1, -1));

        jTextFieldH2.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTextFieldH2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldH2.setText("100.0");
        jPanelConfig2.add(jTextFieldH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 25, 50, -1));

        jPanelMain.add(jPanelConfig2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 340, 70));

        jPanelConfig3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "超购倍数", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 12))); // NOI18N
        jPanelConfig3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox3.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "全部", "区间下值", "区间中值", "区间上值" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanelConfig3.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 25, -1, -1));

        jLabelL3.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabelL3.setText("下值：");
        jPanelConfig3.add(jLabelL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 28, -1, -1));

        jTextFieldL3.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTextFieldL3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldL3.setText("0");
        jPanelConfig3.add(jTextFieldL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 25, 50, -1));

        jLabelH3.setText("上值：");
        jPanelConfig3.add(jLabelH3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 28, -1, -1));

        jTextFieldH3.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTextFieldH3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldH3.setText("100.0");
        jPanelConfig3.add(jTextFieldH3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 25, 50, -1));

        jPanelMain.add(jPanelConfig3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 340, 70));

        jPanelConfig4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "募资总额", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 12))); // NOI18N
        jPanelConfig4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox4.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "全部", "区间下值", "区间中值", "区间上值" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanelConfig4.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 25, -1, -1));

        jLabelL4.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabelL4.setText("下值：");
        jPanelConfig4.add(jLabelL4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 28, -1, -1));

        jTextFieldL4.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTextFieldL4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldL4.setText("0");
        jPanelConfig4.add(jTextFieldL4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 25, 50, -1));

        jLabelH4.setText("上值：");
        jPanelConfig4.add(jLabelH4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 28, -1, -1));

        jTextFieldH4.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTextFieldH4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldH4.setText("100.0");
        jPanelConfig4.add(jTextFieldH4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 25, 50, -1));

        jPanelMain.add(jPanelConfig4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 340, 70));

        jPanelConfig5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "暗盘涨幅", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 12))); // NOI18N
        jPanelConfig5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox5.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "全部", "区间下值", "区间中值", "区间上值" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        jPanelConfig5.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 25, -1, -1));

        jLabelL5.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabelL5.setText("下值：");
        jPanelConfig5.add(jLabelL5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 28, -1, -1));

        jTextFieldL5.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTextFieldL5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldL5.setText("0");
        jPanelConfig5.add(jTextFieldL5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 25, 50, -1));

        jLabelH5.setText("上值：");
        jPanelConfig5.add(jLabelH5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 28, -1, -1));

        jTextFieldH5.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTextFieldH5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldH5.setText("100.0");
        jPanelConfig5.add(jTextFieldH5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 25, 50, -1));

        jPanelMain.add(jPanelConfig5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 340, 70));

        jPanelConfig6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "一手金额", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 12))); // NOI18N
        jPanelConfig6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox6.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "全部", "区间下值", "区间中值", "区间上值" }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        jPanelConfig6.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 25, -1, -1));

        jLabelL6.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabelL6.setText("下值：");
        jPanelConfig6.add(jLabelL6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 28, -1, -1));

        jTextFieldL6.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTextFieldL6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldL6.setText("2000");
        jPanelConfig6.add(jTextFieldL6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 25, 50, -1));

        jLabelH6.setText("上值：");
        jPanelConfig6.add(jLabelH6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 28, -1, -1));

        jTextFieldH6.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTextFieldH6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldH6.setText("5000");
        jPanelConfig6.add(jTextFieldH6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 25, 50, -1));

        jPanelMain.add(jPanelConfig6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 340, 70));

        jButtonUnderwriter.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jButtonUnderwriter.setText("承销商");
        jButtonUnderwriter.setMargin(new java.awt.Insets(2, 8, 2, 8));
        jButtonUnderwriter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUnderwriterActionPerformed(evt);
            }
        });
        jPanelMain.add(jButtonUnderwriter, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 70, 30));

        getContentPane().add(jPanelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 510));

        jMenuFile.setText("文件");

        jMenuItemOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemOpen.setText("打开...");
        jMenuItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpenActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemOpen);

        jMenuBar.add(jMenuFile);

        jMenuRun.setText("运行");

        jMenuItemDZH.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemDZH.setText("大智慧");
        jMenuItemDZH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDZHActionPerformed(evt);
            }
        });
        jMenuRun.add(jMenuItemDZH);

        jMenuBar.add(jMenuRun);

        jMenuHelp.setText("帮助");

        jMenuItemAbout.setText("关于");
        jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItemAbout);

        jMenuBar.add(jMenuHelp);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpenActionPerformed
    }//GEN-LAST:event_jMenuItemOpenActionPerformed

    private void jMenuItemDZHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDZHActionPerformed
        runExeFile("C:\\dzh365\\dzh2.exe");
    }//GEN-LAST:event_jMenuItemDZHActionPerformed

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
        JOptionPane.showMessageDialog(new JFrame(), "智能证券系统-港股打新 V21.02\n版权所有(C) 张向荣(Aioros Zhang)");
    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    private void jButtonIpoInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIpoInfoActionPerformed
        ArrayList<IpoInfo> ipoInfos = getSelectedIpoInfos();
        if (ipoInfos.isEmpty()) {
            JOptionPane.showMessageDialog(new JFrame(), "没有满足条件的新股！");
            return;
        }
        IpoTable ipoTable = new IpoTable(this, false, ipoInfos);
    }//GEN-LAST:event_jButtonIpoInfoActionPerformed

    private void jButtonIpoEvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIpoEvaActionPerformed
        ArrayList<IpoInfo> ipoInfos = getSelectedIpoInfos();
        if (ipoInfos.isEmpty()) {
            JOptionPane.showMessageDialog(new JFrame(), "没有满足条件的新股！");
            return;
        }

        strategy = new Strategy(ipoInfos);
        ArrayList<SystemReport> systemReports = new ArrayList<>();
        for (int i = 0; i < 3; i++) {
            SystemReport systemReport = updateSystemReport(strategy, i);
            systemReports.add(systemReport);
        }

        StatisTable statisTable = new StatisTable(this, false, systemReports);

        evaluated = true;
    }//GEN-LAST:event_jButtonIpoEvaActionPerformed

    private void jButtonBigDataAnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBigDataAnalysisActionPerformed
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        SystemReport sr;
        ArrayList<SystemReport> srList = new ArrayList<>();

        int sellPoint = jComboBoxS3.getSelectedIndex();
        strategy = new Strategy(ipoInfoList);
        float oldOWeightRestictEarn = 0;
        switch (jComboBox10.getSelectedIndex()) {
            case 0:
                for (int i = 1; i <= 100; i++) {
                    sr = updateSimpleReport(strategy, 1, (float) i);
                    if (sr.OWeightEarnRestict != oldOWeightRestictEarn) {
                        oldOWeightRestictEarn = sr.OWeightEarnRestict;
                        srList.add(sr);
                    }
                }
                break;
            case 1:
                for (int i = 1; i < 1000; i++) {
                    sr = updateSimpleReport(strategy, 2, (float) i);
                    if (sr.OWeightEarnRestict != oldOWeightRestictEarn) {
                        oldOWeightRestictEarn = sr.OWeightEarnRestict;
                        srList.add(sr);
                    }
                }
                break;
            case 2:
                for (int i = 1; i <= 1000; i++) {
                    sr = updateSimpleReport(strategy, 3, (float) i / 10);
                    if (sr.OWeightEarnRestict != oldOWeightRestictEarn) {
                        oldOWeightRestictEarn = sr.OWeightEarnRestict;
                        srList.add(sr);
                    }
                }
                break;
            default:
                for (int i = 1; i < 1000; i++) {
                    sr = updateSimpleReport(strategy, 4, (float) i / 10);
                    if (sr.OWeightEarnRestict != oldOWeightRestictEarn) {
                        oldOWeightRestictEarn = sr.OWeightEarnRestict;
                        srList.add(sr);
                    }
                }
                break;
        }

        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));

        //Collections.sort(srList, (SystemReport arg0, SystemReport arg1) -> new Float(arg1.OWeightEarnRestict).compareTo(arg0.OWeightEarnRestict));
        RankTable rankTable = new RankTable(this, false, this, srList);
    }//GEN-LAST:event_jButtonBigDataAnalysisActionPerformed

    private void jButtonGrayAnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGrayAnalysisActionPerformed
        int items = ipoInfoList.size();
        int t_num = 0;
        int num = 0;
        float money = 0;
        float level = (float) 0.4;
        float t_gain = 0;
        for (int gg = 30; gg <= 60; gg++) {
            //System.out.println("gg:" + gg);
            for (int f = 38; f <= 38; f++) {
                level = (float) f / 100;
                num = 0;
                money = 0;
                t_num = 0;
                t_gain = 0;
                for (int i = 0; i < items; i++) {
                    if (ipoInfoList.get(i).grayGain > gg) {
                        t_num++;
                        float bp = ipoInfoList.get(i).grayPrice;
                        float op = ipoInfoList.get(i).openPrice;
                        float hp = ipoInfoList.get(i).highPrice;
                        float lp = ipoInfoList.get(i).lowPrice;
                        float cp = ipoInfoList.get(i).closePrice;
                        float hf = ipoInfoList.get(i).handFundReal / ipoInfoList.get(i).offerPrice;
                        String openGain = String.format("%.1f", 100 * (op / bp - 1));
                        String highGain = String.format("%.1f", 100 * (hp / bp - 1));
                        String lowGain = String.format("%.1f", 100 * (lp / bp - 1));
                        String closeGain = String.format("%.1f", 100 * (cp / bp - 1));
                        float earn = 0;
                        float gain = 0;
                        if (op / bp - 1 >= level) {
                            num++;
                            earn = hf * (op - bp);
                            gain = (op - bp) / bp;
                        } else if (hp / bp - 1 >= level) {
                            num++;
                            earn = hf * bp * level;
                            gain = level;
                        } else {
                            earn = hf * (cp - bp);
                            gain = (cp - bp) / bp;
                        }
                        //String stockInfo = String.format("greyGain: %.2f%%\topenGain: %5s%%\thighGain: %5s%%\tcloseGain: %5s%%\tearn: %.2f\tgain: %6.2f%%\t%-10s", ipoInfoList.get(i).grayGain, openGain, highGain, closeGain, earn, 100 * gain, ipoInfoList.get(i).stockName);
                        //System.out.println(stockInfo);

                        money += earn;
                        t_gain += gain;
                    }
                }
                String schemeInfo = String.format("greyGain: %d%%\tlevel: %d%%\tnum: %d/%d\tpercent: %.2f%%\tmoney: %.2f\te_money: %6.2f\tt_gain: %.2f%%\te_gain: %.2f%%", gg, f, num, t_num, (float) num / t_num, money, money / t_num, 100 * t_gain, 100 * t_gain / t_num);
                System.out.println(schemeInfo);
            }
        }
    }//GEN-LAST:event_jButtonGrayAnalysisActionPerformed

    private void jButtonFilterStart2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFilterStart2ActionPerformed
        int items = ipoInfoList.size();
        int t_num = 0;
        int num = 0;
        float money = 0;
        float level = (float) 0.4;

        for (int f = 100; f <= 250; f++) {
            level = (float) f / 100;
            num = 0;
            money = 0;
            t_num = 0;
            for (int i = 0; i < items; i++) {
                t_num++;
                float ip = ipoInfoList.get(i).offerPrice;
                float op = ipoInfoList.get(i).openPrice;
                float hp = ipoInfoList.get(i).highPrice;
                float lp = ipoInfoList.get(i).lowPrice;
                float cp = ipoInfoList.get(i).closePrice;
                float hf = ipoInfoList.get(i).handFund / ipoInfoList.get(i).offerPrice;
                float lr = ipoInfoList.get(i).luckyRate / 100;
                float rf = ipoInfoList.get(i).totalRaiseFunds;
                String openGain = String.format("%.1f", 100 * (op / ip - 1));
                String highGain = String.format("%.1f", 100 * (hp / ip - 1));
                String lowGain = String.format("%.1f", 100 * (lp / ip - 1));
                String closeGain = String.format("%.1f", 100 * (cp / ip - 1));
                //System.out.println("openGain: " + openGain + "\thighGain: " + highGain  + "\tcloseGain: " + closeGain + "\t" + ipoInfoList.get(i).stockName);
                if ((op / ip - 1 >= level) || (rf < 1.4)) {
                    num++;
                    money += hf * (op - ip) * lr;
                    //System.out.println("openGain: " + openGain + "\thighGain: " + highGain  + "\tcloseGain: " + closeGain + "\t" + ipoInfoList.get(i).blackGain + "\t" + ipoInfoList.get(i).stockName);
                } else if (hp / ip - 1 >= level) {
                    num++;
                    money += hf * ip * level * lr;
                    System.out.println("openGain: " + openGain + "\thighGain: " + highGain + "\tcloseGain: " + closeGain + "\t" + ipoInfoList.get(i).grayGain + "\t" + ipoInfoList.get(i).stockName);
                } else {
                    money += hf * (cp - ip) * lr;
                    //System.out.println("openGain: " + openGain + "\thighGain: " + highGain  + "\tcloseGain: " + closeGain + "\t" + ipoInfoList.get(i).blackGain + "\t" + ipoInfoList.get(i).stockName);
                }
            }
            System.out.println("level: " + f + "\tnum: " + num + "\tpercent: " + (float) num / t_num + "\tmoney: " + money);

        }
    }//GEN-LAST:event_jButtonFilterStart2ActionPerformed

    private void jComboBox0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox0ActionPerformed

    }//GEN-LAST:event_jComboBox0ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jComboBoxS3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxS3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxS3ActionPerformed

    private void jComboBoxS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxS1ActionPerformed

    private void jComboBoxS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxS2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxS2ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jComboBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox10ActionPerformed

    private void jButtonUnderwriterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUnderwriterActionPerformed
        ArrayList<IpoInfo> ipoInfos = getSelectedIpoInfos();
        if (ipoInfos.isEmpty()) {
            JOptionPane.showMessageDialog(new JFrame(), "没有满足条件的新股！");
            return;
        }

        for (Underwriter underwriter : underwriterList) {
            underwriter.getStatisInfo();
        }

        UnderwrTable underwrTable = new UnderwrTable(this, false, underwriterList);

        evaluated = true;
    }//GEN-LAST:event_jButtonUnderwriterActionPerformed

    /**
     ********************* Start of User-defined function ********************
     */
    protected void importData() {
        try {
            File file = new File(fileIn);
            InputStreamReader isr = new InputStreamReader(new FileInputStream(file), "gbk");
            BufferedReader br = new BufferedReader(isr);
            String[] words = br.readLine().split("\t+");
            ipoInfoList = new ArrayList<>();
            String line;
            while ((line = br.readLine()) != null) {
                words = line.split("\t+");
                IpoInfo ipoInfo = new IpoInfo(words[0], words[1]);
                ipoInfo.marketPlate = words[2];
                ipoInfo.offerDate = words[3];
                ipoInfo.inquiryRange = words[4];
                ipoInfo.handFund = Integer.parseInt(words[5]);
                ipoInfo.luckyRate = Float.parseFloat(words[6].substring(0, words[6].length() - 1));
                ipoInfo.offerPrice = Float.parseFloat(words[7]);
                ipoInfo.offerPE = words[8];
                ipoInfo.greenShoeRatio = words[9].equals("-") ? 0 : Float.parseFloat(words[9].substring(0, words[9].length() - 1));;
                ipoInfo.comparableCompany = words[10];
                ipoInfo.superPurchaseMultiples = Float.parseFloat(words[11]);
                ipoInfo.totalRaiseFunds = Float.parseFloat(words[12]);
                ipoInfo.grayGain = Float.parseFloat(words[13].substring(0, words[13].length() - 1));
                ipoInfo.closeGain = Float.parseFloat(words[14].substring(0, words[14].length() - 1));
                ipoInfo.openPrice = Float.parseFloat(words[15]);
                ipoInfo.highPrice = Float.parseFloat(words[16]);
                ipoInfo.lowPrice = Float.parseFloat(words[17]);
                ipoInfo.closePrice = Float.parseFloat(words[18]);
                ipoInfo.underwriter = words[19];

                ipoInfo.getLevel2();
                ipoInfoList.add(ipoInfo);
            }
            br.close();
            isr.close();
        } catch (IOException | NumberFormatException e) {
            e.printStackTrace();
        }

        evaluated = false;
    }

    protected void getUnderwriter() {
        underwriterList = new ArrayList<>();
        for (IpoInfo ipoInfo : ipoInfoList) {
            String[] uws = ipoInfo.underwriter.split("/");
            for (int i = 0; i < uws.length; i++) {
                boolean matched = false;
                for (Underwriter underwriter : underwriterList) {
                    if (underwriter.name.equals(uws[i])) {
                        underwriter.ipoInfoList.add(ipoInfo);
                        matched = true;
                        break;
                    }
                }
                if (!matched) {
                    Underwriter underwriter = new Underwriter(uws[i]);
                    underwriter.ipoInfoList.add(ipoInfo);
                    underwriterList.add(underwriter);
                }
            }
        }
    }

    public boolean inSection(int sectType, float sectL, float sectH, float value) {
        if (sectType == 1) {
            if (value >= sectL) {
                return false;
            }
        } else if (sectType == 2) {
            if ((value < sectL) || (value > sectH)) {
                return false;
            }
        } else if (sectType == 3) {
            if (value <= sectH) {
                return false;
            }
        }
        return true;
    }

    public static boolean inDateScope(int scopeType, String dateStr) {
        if (scopeType == 0) {
            return true;
        }

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        String currentDate = sdf.format(new Date());
        String[] ymd = currentDate.split("/");
        int year = Integer.parseInt(ymd[0]);
        int month = Integer.parseInt(ymd[1]);
        int date = Integer.parseInt(ymd[2]);
        switch (scopeType) {
            case 1:
                year = (month > 3) ? year : year - 1;
                month = (month > 3) ? (month - 3) : (month + 9);
                break;
            case 2:
                year = (month > 6) ? year : year - 1;
                month = (month > 6) ? (month - 6) : (month + 6);
                break;
            case 3:
                year = year - 1;
                break;
            case 4:
                year = year - 2;
                break;
            default:
                break;
        }
        String lastDate = String.format("%d/%02d/%02d", year, month, date);
        return dateStr.compareTo(lastDate) > 0;
    }

    public ArrayList<IpoInfo> getSelectedIpoInfos() {
        ArrayList<IpoInfo> ipoInfos = new ArrayList<>();
        for (IpoInfo ipoInfo : ipoInfoList) {
            int type = jComboBox0.getSelectedIndex();
            float cpl = Float.parseFloat(jTextFieldL0.getText());
            float cph = Float.parseFloat(jTextFieldH0.getText());
            if (!inSection(type, cpl, cph, ipoInfo.luckyRate)) {
                continue;
            }

            type = jComboBox1.getSelectedIndex();
            cpl = Float.parseFloat(jTextFieldL1.getText());
            cph = Float.parseFloat(jTextFieldH1.getText());
            if (!inSection(type, cpl, cph, ipoInfo.offerPrice)) {
                continue;
            }

            type = jComboBox2.getSelectedIndex();
            cpl = Float.parseFloat(jTextFieldL2.getText());
            cph = Float.parseFloat(jTextFieldH2.getText());
            if (!inSection(type, cpl, cph, ipoInfo.greenShoeRatio)) {
                continue;
            }

            type = jComboBox3.getSelectedIndex();
            cpl = Float.parseFloat(jTextFieldL3.getText());
            cph = Float.parseFloat(jTextFieldH3.getText());
            if (!inSection(type, cpl, cph, ipoInfo.superPurchaseMultiples)) {
                continue;
            }

            type = jComboBox4.getSelectedIndex();
            cpl = Float.parseFloat(jTextFieldL4.getText());
            cph = Float.parseFloat(jTextFieldH4.getText());
            if (!inSection(type, cpl, cph, ipoInfo.totalRaiseFunds)) {
                continue;
            }

            type = jComboBox5.getSelectedIndex();
            cpl = Float.parseFloat(jTextFieldL5.getText());
            cph = Float.parseFloat(jTextFieldH5.getText());
            if (!inSection(type, cpl, cph, ipoInfo.grayGain)) {
                continue;
            }

            type = jComboBox6.getSelectedIndex();
            cpl = Float.parseFloat(jTextFieldL6.getText());
            cph = Float.parseFloat(jTextFieldH6.getText());
            if (!inSection(type, cpl, cph, ipoInfo.handFund)) {
                continue;
            }

            int plate = jComboBoxS1.getSelectedIndex();
            if (((ipoInfo.marketPlate.equals("主板")) && (plate == 2)) || ((ipoInfo.marketPlate.equals("创业板")) && (plate == 1))) {
                continue;
            }

            if (jComboBoxS2.getSelectedIndex() < 5) {
                if ((!inDateScope(jComboBoxS2.getSelectedIndex(), ipoInfo.offerDate))) {
                    continue;
                }
            } else if (!ipoInfo.offerDate.contains(jComboBoxS2.getSelectedItem().toString())) {
                continue;
            }

            ipoInfos.add(ipoInfo);
        }

        return ipoInfos;
    }

    protected SystemReport updateSystemReport(Strategy strategy, int sp) {
        SystemReport systemReport = new SystemReport();

        systemReport.totalStocks = ipoInfoList.size();
        systemReport.selectedStocks = strategy.getSelectedStocks();
        systemReport.gainStocks = strategy.getGainStocks(sp);
        systemReport.dropStocks = strategy.getDropStocks(sp);

        systemReport.totalGain = strategy.getTotalGain(sp);
        systemReport.totalEarn = strategy.getTotalEarn(sp);
        systemReport.weightGain = strategy.getWeightGain(sp);
        systemReport.weightEarn = strategy.getWeightEarn(sp);
        systemReport.evenTotalGain = strategy.getEvenTotalGain(sp);
        systemReport.evenTotalEarn = strategy.getEvenTotalEarn(sp);
        systemReport.evenWeightGain = strategy.getEvenWeightGain(sp);
        systemReport.evenWeightEarn = strategy.getEvenWeightEarn(sp);

        systemReport.maxStockGain = strategy.getMaxStockGain(sp);
        systemReport.maxStockEarn = strategy.getMaxStockEarn(sp);
        systemReport.maxWeightGain = strategy.getMaxWeightGain(sp);
        systemReport.maxWeightEarn = strategy.getMaxWeightEarn(sp);
        systemReport.maxStockDrop = strategy.getMaxStockDrop(sp);
        systemReport.maxStockLoss = strategy.getMaxStockLoss(sp);
        systemReport.maxWeightDrop = strategy.getMaxWeightDrop(sp);
        systemReport.maxWeightLoss = strategy.getMaxWeightLoss(sp);
        return systemReport;
    }

    protected SystemReport updateSimpleReport(Strategy stg, int type, float cp) {
        SystemReport sr = new SystemReport(cp);

        sr.OWeightEarnRestict = strategy.getOWeightEarnRestict(type, cp);
        sr.CWeightEarnRestict = strategy.getCWeightEarnRestict(type, cp);
        sr.OCWeightEarnRestict = strategy.getOCWeightEarnRestict(type, cp);
        sr.COWeightEarnRestict = strategy.getCOWeightEarnRestict(type, cp);
        return sr;
    }

    public void msgLogger(String str) {
        //jTextAreaMain.append(str + System.getProperty("line.separator"));
    }

    public void fileLogger(String str) {
        if (fileWriter != null) {
            try {
                fileWriter.write(str + System.getProperty("line.separator"));
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }

    public void runExeFile(String file) {
        try {
            Runtime rt = Runtime.getRuntime();
            File exeFile = new File(file);
            if (exeFile.exists()) {
                String cmd = "cmd.exe /c " + file;
                rt.exec(cmd);
            } else {
                JOptionPane.showMessageDialog(new JFrame(), "请先安装相关软件到根目录！");
            }
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    private String fileIn = "data\\港股新股.txt";
    public FileWriter fileWriter;

    public Strategy strategy;
    public boolean evaluated = false;
    //public RankTable rankTable;
    public ArrayList<CheckData> chkDataList;

    ArrayList<IpoInfo> ipoInfoList;
    ArrayList<Underwriter> underwriterList;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonBigDataAnalysis;
    private javax.swing.JButton jButtonFilterStart2;
    private javax.swing.JButton jButtonGrayAnalysis;
    private javax.swing.JButton jButtonIpoEva;
    private javax.swing.JButton jButtonIpoInfo;
    private javax.swing.JButton jButtonUnderwriter;
    private javax.swing.JComboBox<String> jComboBox0;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBoxS1;
    private javax.swing.JComboBox<String> jComboBoxS2;
    private javax.swing.JComboBox<String> jComboBoxS3;
    private javax.swing.JLabel jLabelH0;
    private javax.swing.JLabel jLabelH1;
    private javax.swing.JLabel jLabelH2;
    private javax.swing.JLabel jLabelH3;
    private javax.swing.JLabel jLabelH4;
    private javax.swing.JLabel jLabelH5;
    private javax.swing.JLabel jLabelH6;
    private javax.swing.JLabel jLabelL0;
    private javax.swing.JLabel jLabelL1;
    private javax.swing.JLabel jLabelL2;
    private javax.swing.JLabel jLabelL3;
    private javax.swing.JLabel jLabelL4;
    private javax.swing.JLabel jLabelL5;
    private javax.swing.JLabel jLabelL6;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemDZH;
    private javax.swing.JMenuItem jMenuItemOpen;
    private javax.swing.JMenu jMenuRun;
    private javax.swing.JPanel jPanelConf1;
    private javax.swing.JPanel jPanelConf2;
    private javax.swing.JPanel jPanelConf3;
    private javax.swing.JPanel jPanelConfig0;
    private javax.swing.JPanel jPanelConfig1;
    private javax.swing.JPanel jPanelConfig2;
    private javax.swing.JPanel jPanelConfig3;
    private javax.swing.JPanel jPanelConfig4;
    private javax.swing.JPanel jPanelConfig5;
    private javax.swing.JPanel jPanelConfig6;
    private javax.swing.JPanel jPanelDebug;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JTextField jTextFieldH0;
    private javax.swing.JTextField jTextFieldH1;
    private javax.swing.JTextField jTextFieldH2;
    private javax.swing.JTextField jTextFieldH3;
    private javax.swing.JTextField jTextFieldH4;
    private javax.swing.JTextField jTextFieldH5;
    private javax.swing.JTextField jTextFieldH6;
    private javax.swing.JTextField jTextFieldL0;
    private javax.swing.JTextField jTextFieldL1;
    private javax.swing.JTextField jTextFieldL2;
    private javax.swing.JTextField jTextFieldL3;
    private javax.swing.JTextField jTextFieldL4;
    private javax.swing.JTextField jTextFieldL5;
    private javax.swing.JTextField jTextFieldL6;
    // End of variables declaration//GEN-END:variables
}
