/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Stagging;

import java.awt.Cursor;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URL;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author zhangxr
 */
public class MainView extends javax.swing.JFrame {

    public class CheckData {

        public CheckData(String m, String para) {
            mode = m;
            parameter = para;
        }
        public String mode;
        public String parameter;
        public String status;
        public int days;
        public double key;
        public double percent;
        public String amount;
    }

    /**
     * Creates new form StockerView
     */
    public MainView() {
        initComponents();
        setLocationRelativeTo(null);
        final URL filename = getClass().getResource("/resource/Livermore3.jpg");
        if (filename != null) {
            setIconImage(new ImageIcon(filename, "Icon").getImage());
        }
        importData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItemCopy = new javax.swing.JMenuItem();
        jMenuItemClear = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelMain = new javax.swing.JPanel();
        jScrollPaneTable = new javax.swing.JScrollPane();
        jTablePoint = new javax.swing.JTable();
        jScrollPaneMsg = new javax.swing.JScrollPane();
        jTextAreaMain = new javax.swing.JTextArea();
        jPanelCongfig = new javax.swing.JPanel();
        jButtonIpoEva = new javax.swing.JButton();
        jButtonIpoInfo = new javax.swing.JButton();
        jLabelCriticalValue = new javax.swing.JLabel();
        jTextFieldCriticalValue = new javax.swing.JTextField();
        jRadioButtonAddLm = new javax.swing.JRadioButton();
        jRadioButtonAddMa = new javax.swing.JRadioButton();
        jRadioButtonAddDif = new javax.swing.JRadioButton();
        jButtonFilterStart = new javax.swing.JButton();
        jRadioButtonAddLm1 = new javax.swing.JRadioButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemOpen = new javax.swing.JMenuItem();
        jMenuRun = new javax.swing.JMenu();
        jMenuItemDZH = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemAbout = new javax.swing.JMenuItem();

        jMenuItemCopy.setText("复制");
        jMenuItemCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCopyActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItemCopy);

        jMenuItemClear.setText("清除");
        jMenuItemClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClearActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItemClear);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("智能证券系统-港股打新");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTablePoint.getTableHeader().setFont(new java.awt.Font("微软雅黑", 0, 12));
        jTablePoint.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTablePoint.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"开盘累计涨幅", null, "收盘累计涨幅", ""},
                {"开盘累计收益", null, "收盘累计收益", null},
                {"开盘加权收益", null, "收盘加权收益", ""},
                {"开盘加权收益R", null, "收盘加权收益R", null},
                {"", null, "", null},
                {"", null, "", null}
            },
            new String [] {
                "统计指标", "全部交易", "统计指标", "全部交易"
            }
        ));
        jTablePoint.setPreferredSize(new java.awt.Dimension(310, 96));
        jScrollPaneTable.setViewportView(jTablePoint);
        if (jTablePoint.getColumnModel().getColumnCount() > 0) {
            jTablePoint.getColumnModel().getColumn(0).setMinWidth(80);
            jTablePoint.getColumnModel().getColumn(2).setMinWidth(80);
        }

        jPanelMain.add(jScrollPaneTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 370, 126));

        jTextAreaMain.setColumns(20);
        jTextAreaMain.setFont(new java.awt.Font("仿宋", 0, 11)); // NOI18N
        jTextAreaMain.setRows(5);
        jTextAreaMain.setComponentPopupMenu(jPopupMenu1);
        jTextAreaMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextAreaMainMouseReleased(evt);
            }
        });
        jScrollPaneMsg.setViewportView(jTextAreaMain);

        jPanelMain.add(jScrollPaneMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 370, 70));

        jPanelCongfig.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "定投配置", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 12))); // NOI18N
        jPanelCongfig.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonIpoEva.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jButtonIpoEva.setText("投资评测");
        jButtonIpoEva.setMargin(new java.awt.Insets(2, 8, 2, 8));
        jButtonIpoEva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIpoEvaActionPerformed(evt);
            }
        });
        jPanelCongfig.add(jButtonIpoEva, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, 30));

        jButtonIpoInfo.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jButtonIpoInfo.setText("新股信息");
        jButtonIpoInfo.setMargin(new java.awt.Insets(2, 8, 2, 8));
        jButtonIpoInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIpoInfoActionPerformed(evt);
            }
        });
        jPanelCongfig.add(jButtonIpoInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 30));

        jLabelCriticalValue.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabelCriticalValue.setText("临界位：");
        jPanelCongfig.add(jLabelCriticalValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jTextFieldCriticalValue.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTextFieldCriticalValue.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldCriticalValue.setText("1.0");
        jPanelCongfig.add(jTextFieldCriticalValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 68, 110, -1));

        buttonGroup1.add(jRadioButtonAddLm);
        jRadioButtonAddLm.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jRadioButtonAddLm.setText("超购倍数");
        jPanelCongfig.add(jRadioButtonAddLm, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        buttonGroup1.add(jRadioButtonAddMa);
        jRadioButtonAddMa.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jRadioButtonAddMa.setText("发行价");
        jPanelCongfig.add(jRadioButtonAddMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        buttonGroup1.add(jRadioButtonAddDif);
        jRadioButtonAddDif.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jRadioButtonAddDif.setSelected(true);
        jRadioButtonAddDif.setText("中签率");
        jPanelCongfig.add(jRadioButtonAddDif, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jButtonFilterStart.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jButtonFilterStart.setText("统计分析");
        jButtonFilterStart.setMargin(new java.awt.Insets(2, 8, 2, 8));
        jButtonFilterStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFilterStartActionPerformed(evt);
            }
        });
        jPanelCongfig.add(jButtonFilterStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 70, 30));

        buttonGroup1.add(jRadioButtonAddLm1);
        jRadioButtonAddLm1.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jRadioButtonAddLm1.setText("募资总额");
        jPanelCongfig.add(jRadioButtonAddLm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jPanelMain.add(jPanelCongfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 370, 160));

        getContentPane().add(jPanelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 390));

        jMenuFile.setText("文件");

        jMenuItemOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemOpen.setText("打开...");
        jMenuItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpenActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemOpen);

        jMenuBar.add(jMenuFile);

        jMenuRun.setText("运行");

        jMenuItemDZH.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemDZH.setText("大智慧");
        jMenuItemDZH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDZHActionPerformed(evt);
            }
        });
        jMenuRun.add(jMenuItemDZH);

        jMenuBar.add(jMenuRun);

        jMenuHelp.setText("帮助");

        jMenuItemAbout.setText("关于");
        jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItemAbout);

        jMenuBar.add(jMenuHelp);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpenActionPerformed
    }//GEN-LAST:event_jMenuItemOpenActionPerformed

    private void jMenuItemDZHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDZHActionPerformed
        runExeFile("C:\\dzh365\\dzh2.exe");
    }//GEN-LAST:event_jMenuItemDZHActionPerformed

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
        JOptionPane.showMessageDialog(new JFrame(), "智能证券系统-港股打新 V19.10\n版权所有(C) 张向荣(Aioros Zhang)");
    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    private void jTextAreaMainMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextAreaMainMouseReleased
        if (evt.isPopupTrigger()) {
            jPopupMenu1.show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jTextAreaMainMouseReleased

    private void jMenuItemClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClearActionPerformed
        jTextAreaMain.setText("");
    }//GEN-LAST:event_jMenuItemClearActionPerformed

    private void jMenuItemCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCopyActionPerformed
        jTextAreaMain.selectAll();
        jTextAreaMain.copy();
    }//GEN-LAST:event_jMenuItemCopyActionPerformed

    private void jButtonIpoInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIpoInfoActionPerformed
        importData();
        IpoTable ipoTable = new IpoTable(this, false, ipoInfoList);
    }//GEN-LAST:event_jButtonIpoInfoActionPerformed

    private void jButtonIpoEvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIpoEvaActionPerformed
        float critPoint = Float.parseFloat(jTextFieldCriticalValue.getText());
        strategy = new Strategy(ipoInfoList);

//        getInvestMode();
//        double p1 = 0, p2 = 0, p3 = 0;
//        String[] words = investPara.split(",");
//        p1 = Double.parseDouble(words[0]);
//        p2 = Double.parseDouble(words[1]);
//        p3 = Double.parseDouble(words[2]);
//        ret = strategy.sysEva(p1, p2, p3);
//        if (!ret) {
//            JOptionPane.showMessageDialog(new JFrame(), "无效的参数设置！");
//            return;
//        }
        SystemReport sr = updateSystemReport(strategy, critPoint);
        updateTable(sr);

        evaluated = true;
    }//GEN-LAST:event_jButtonIpoEvaActionPerformed

    private void jButtonFilterStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFilterStartActionPerformed
        jTextAreaMain.setText("");

        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        SystemReport sr;
        ArrayList<SystemReport> srList = new ArrayList<>();
//
//        for (double i = ps1; i <= pe1; i += 10) {
//            for (double j = ps2; j <= pe2; j += 0.1) {
//                strategy = new Strategy(this, start, slope);
//                if (strategy.sysSimpleInvestEva(i, j, k)) {
//                    String para = String.format("%d,%.1f,%.1f", (int) i, j, k);
//                    sr = updateSimpleReport(para, strategy);
//                    srList.add(sr);
//                }
//            }
//        }

        strategy = new Strategy(ipoInfoList);
        float oldOWeightRestictEarn = 0;
        for (int i = 1; i < 100; i++) {
            sr = updateSimpleReport((float) i / 10, strategy);
            if (sr.OWeightRestictEarn != oldOWeightRestictEarn) {
                oldOWeightRestictEarn = sr.OWeightRestictEarn;
                srList.add(sr);
            }
        }
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));

        Collections.sort(srList, (SystemReport arg0, SystemReport arg1) -> new Float(arg1.OWeightEarn).compareTo(arg0.OWeightEarn));
        RankTable rankTable = new RankTable(this, false, this, srList);
    }//GEN-LAST:event_jButtonFilterStartActionPerformed

    /**
     ********************* Start of User-defined function ********************
     */
    protected void importData() {
        try {
            File file = new File(fileIn);
            InputStreamReader isr = new InputStreamReader(new FileInputStream(file), "gbk");
            BufferedReader br = new BufferedReader(isr);
            String[] words = br.readLine().split("\t");
            column = words.length;
            ipoInfoList = new ArrayList<>();
            String line;
            while ((line = br.readLine()) != null) {
                words = line.split("\t+");
                IpoInfo ipoInfo = new IpoInfo(words[0], words[1]);
                ipoInfo.marketPlate = words[2];
                ipoInfo.offerDate = words[3];
                ipoInfo.handFund = Float.parseFloat(words[4]);
                ipoInfo.luckyRate = Float.parseFloat(words[5].substring(0, words[5].length() - 1));
                ipoInfo.offerPrice = Float.parseFloat(words[6]);
                ipoInfo.superPurchaseMultiples = Float.parseFloat(words[7]);
                ipoInfo.totalRaiseFunds = Float.parseFloat(words[8]);
                ipoInfo.blackGain = Float.parseFloat(words[9].substring(0, words[9].length() - 1));
                ipoInfo.blackPrice = ipoInfo.offerPrice * (1 + ipoInfo.blackGain / 100);
                ipoInfo.closeGain = Float.parseFloat(words[10].substring(0, words[10].length() - 1));
                ipoInfo.openPrice = Float.parseFloat(words[11]);
                ipoInfo.openGain = 100 * (ipoInfo.openPrice - ipoInfo.offerPrice) / ipoInfo.offerPrice;
                ipoInfo.closePrice = Float.parseFloat(words[14]);
                ipoInfoList.add(ipoInfo);
            }
            stocks = ipoInfoList.size();
            br.close();
            isr.close();
        } catch (IOException | NumberFormatException e) {
            e.printStackTrace();
        }

        evaluated = false;
    }

    public void investParaEva(String para) {
        String[] paras = para.replaceAll(" ", "").split(",");
        jTextFieldCriticalValue.setText(paras[2]);

        jButtonIpoEva.doClick();
    }

    public void getInvestMode() {
    }

    protected SystemReport updateSystemReport(Strategy stg, float cv) {
        SystemReport sr = new SystemReport(cv);

        sr.OTotalGain = stg.getOTotalGain();
        sr.CTotalGain = stg.getCTotalGain();
        sr.OTotalEarn = stg.getOTotalEarn();
        sr.CTotalEarn = stg.getCTotalEarn();
        sr.OWeightEarn = stg.getOWeightEarn();
        sr.CWeightEarn = stg.getCWeightEarn();
        sr.OWeightRestictEarn = stg.getOWeightRestictEarn(cv);
        sr.CWeightRestictEarn = stg.getCWeightRestictEarn(cv);
        return sr;
    }

    protected SystemReport updateSimpleReport(float i, Strategy stg) {
        SystemReport sr = new SystemReport(i);

        sr.OWeightRestictEarn = strategy.getOWeightRestictEarn(i);
        sr.CWeightRestictEarn = strategy.getCWeightRestictEarn(i);
        sr.OCWeightRestictEarn = strategy.getOCWeightRestictEarn(i);
        sr.COWeightRestictEarn = strategy.getCOWeightRestictEarn(i);
        return sr;
    }

    protected void updateTable(SystemReport sr) {
        jTablePoint.setValueAt("开盘累计涨幅", 0, 0);
        jTablePoint.setValueAt(sr.OTotalGain + "%", 0, 1);
        jTablePoint.setValueAt("收盘累计涨幅", 0, 2);
        jTablePoint.setValueAt(sr.CTotalGain + "%", 0, 3);
        jTablePoint.setValueAt("开盘累计收益", 1, 0);
        jTablePoint.setValueAt(sr.OTotalEarn + "元", 1, 1);
        jTablePoint.setValueAt("收盘累计收益", 1, 2);
        jTablePoint.setValueAt(sr.CTotalEarn + "元", 1, 3);
        jTablePoint.setValueAt("开盘加权收益", 2, 0);
        jTablePoint.setValueAt(sr.OWeightEarn + "元", 2, 1);
        jTablePoint.setValueAt("收盘加权收益", 2, 2);
        jTablePoint.setValueAt(sr.CWeightEarn + "元", 2, 3);
        jTablePoint.setValueAt("开盘加权收益R", 3, 0);
        jTablePoint.setValueAt(sr.OWeightRestictEarn + "元", 3, 1);
        jTablePoint.setValueAt("收盘加权收益R", 3, 2);
        jTablePoint.setValueAt(sr.CWeightRestictEarn + "元", 3, 3);
    }

    public void msgLogger(String str) {
        jTextAreaMain.append(str + System.getProperty("line.separator"));
    }

    public void fileLogger(String str) {
        if (fileWriter != null) {
            try {
                fileWriter.write(str + System.getProperty("line.separator"));
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }

    public void runExeFile(String file) {
        try {
            Runtime rt = Runtime.getRuntime();
            File exeFile = new File(file);
            if (exeFile.exists()) {
                String cmd = "cmd.exe /c " + file;
                rt.exec(cmd);
            } else {
                JOptionPane.showMessageDialog(new JFrame(), "请先安装相关软件到根目录！");
            }
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    private String fileIn = "data\\others\\港股新股.txt";
    public FileWriter fileWriter;

    public String stockName = "W上证指数";
    public String stockCode = "000001";
    public int column = 0;
    public int stocks = 0;

    public int sIdx = -1;
    public int eIdx = 0;
    public int investDays = 0;
    public double testYears = 0;
    public double investCoef = 1;

    public Strategy strategy;
    public boolean evaluated = false;
    //public RankTable rankTable;
    public String investPara;
    public ArrayList<CheckData> chkDataList;

    ArrayList<IpoInfo> ipoInfoList;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonFilterStart;
    private javax.swing.JButton jButtonIpoEva;
    private javax.swing.JButton jButtonIpoInfo;
    private javax.swing.JLabel jLabelCriticalValue;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemClear;
    private javax.swing.JMenuItem jMenuItemCopy;
    private javax.swing.JMenuItem jMenuItemDZH;
    private javax.swing.JMenuItem jMenuItemOpen;
    private javax.swing.JMenu jMenuRun;
    private javax.swing.JPanel jPanelCongfig;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButton jRadioButtonAddDif;
    private javax.swing.JRadioButton jRadioButtonAddLm;
    private javax.swing.JRadioButton jRadioButtonAddLm1;
    private javax.swing.JRadioButton jRadioButtonAddMa;
    private javax.swing.JScrollPane jScrollPaneMsg;
    private javax.swing.JScrollPane jScrollPaneTable;
    private javax.swing.JTable jTablePoint;
    private javax.swing.JTextArea jTextAreaMain;
    private javax.swing.JTextField jTextFieldCriticalValue;
    // End of variables declaration//GEN-END:variables
}
