/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Stagging;

import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author zhangxr
 */
public class StatisTable extends javax.swing.JDialog {

    /**
     * Creates new form StatisTable
     */
    public StatisTable(java.awt.Frame parent, boolean modal, ArrayList<SystemReport> systemReports) {
        super(parent, modal);
        initComponents();

        jTableStatis.getTableHeader().setFont(new java.awt.Font("微软雅黑", 0, 12));
        jTableStatis.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        String[][] tableContent = new String[21][4];
        for (int i = 0; i < 21; i++) {
            tableContent[i][0] = indexNames[i];
        }

        for (int i = 0; i < 3; i++) {
            tableContent[0][i + 1] = systemReports.get(i).totalStocks + "";
            tableContent[1][i + 1] = systemReports.get(i).selectedStocks + "";
            tableContent[2][i + 1] = String.format("%.2f%%", 100 * ((float) systemReports.get(i).selectedStocks / systemReports.get(i).totalStocks));
            tableContent[3][i + 1] = systemReports.get(i).gainStocks + "-" + systemReports.get(i).dropStocks;
            tableContent[4][i + 1] = String.format("%.2f%%", 100 * ((float) systemReports.get(i).gainStocks / systemReports.get(i).selectedStocks));
            tableContent[5][i + 1] = String.format("%.2f%%", systemReports.get(i).totalGain);
            tableContent[6][i + 1] = String.format("%.1f元", systemReports.get(i).totalEarn);
            tableContent[7][i + 1] = String.format("%.2f%%", systemReports.get(i).weightGain);
            tableContent[8][i + 1] = String.format("%.1f元", systemReports.get(i).weightEarn);
            tableContent[9][i + 1] = String.format("%.2f%%", systemReports.get(i).evenTotalGain);
            tableContent[10][i + 1] = String.format("%.1f元", systemReports.get(i).evenTotalEarn);
            tableContent[11][i + 1] = String.format("%.2f%%", systemReports.get(i).evenWeightGain);
            tableContent[12][i + 1] = String.format("%.1f元", systemReports.get(i).evenWeightEarn);
            tableContent[13][i + 1] = String.format("%.2f%%", systemReports.get(i).maxStockGain);
            tableContent[14][i + 1] = String.format("%.1f元", systemReports.get(i).maxStockEarn);
            tableContent[15][i + 1] = String.format("%.2f%%", systemReports.get(i).maxWeightGain);
            tableContent[16][i + 1] = String.format("%.1f元", systemReports.get(i).maxWeightEarn);
            tableContent[17][i + 1] = String.format("%.2f%%", systemReports.get(i).maxStockDrop);
            tableContent[18][i + 1] = String.format("%.1f元", systemReports.get(i).maxStockLoss);
            tableContent[19][i + 1] = String.format("%.2f%%", systemReports.get(i).maxWeightDrop);
            tableContent[20][i + 1] = String.format("%.1f元", systemReports.get(i).maxWeightLoss);
        }
        jTableStatis.setModel(new javax.swing.table.DefaultTableModel(
                tableContent,
                new String[]{
                    "统计指标", "暗盘交易", "开盘交易", "收盘交易"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });

        jScrollPaneStatis.setViewportView(jTableStatis);
        setPreferredSize(new java.awt.Dimension(446, 20 * 21 + 88));
        jScrollPaneStatis.setPreferredSize(new java.awt.Dimension(410, 20 * 21 + 30));
        getContentPane().add(jScrollPaneStatis, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        pack();
        setLocationRelativeTo(parent);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneStatis = new javax.swing.JScrollPane();
        jTableStatis = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("统计信息");

        jScrollPaneStatis.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jScrollPaneStatis.setPreferredSize(new java.awt.Dimension(452, 20));

        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(JLabel.CENTER);
        jTableStatis.setDefaultRenderer(Object.class, tcr);
        jTableStatis.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTableStatis.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTableStatis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "统计指标", "暗盘交易", "开盘交易", "收盘交易"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableStatis.setRowHeight(20);
        jScrollPaneStatis.setViewportView(jTableStatis);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneStatis, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneStatis, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String[] indexNames = new String[]{
        "样本总数", "选中总数", "选中比例", "涨跌个数比", "上涨数比例",
        "累计涨幅", "累计收益", "加权涨幅", "加权收益", "平均累计涨幅", "平均累计收益", "平均加权涨幅", "平均加权收益",
        "最大个股涨幅", "最大个股收益", "最大加权涨幅", "最大加权收益", "最大个股跌幅", "最大个股亏损", "最大加权跌幅", "最大加权亏损"
    };

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPaneStatis;
    private javax.swing.JTable jTableStatis;
    // End of variables declaration//GEN-END:variables
}
