/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stocker;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author zhangxr
 */
public class StockerView extends javax.swing.JFrame {

    /**
     * Creates new form StockerView
     */
    public StockerView() {
        initComponents();
        setLocationRelativeTo(null);

        final URL filename = this.getClass().getResource("resources/Livermore1.jpg");
        if (filename != null) {
            setIconImage(new ImageIcon(filename, "Icon").getImage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelHigh = new javax.swing.JLabel();
        jLabelLow = new javax.swing.JLabel();
        jLabelOpen = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabelStatus = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePoint = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldStartDate = new javax.swing.JTextField();
        jTextFieldEndDate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaMain = new javax.swing.JTextArea();
        jButtonRead = new javax.swing.JButton();
        jComboBoxMode = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        jButtonContinuous = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jLabelStockName = new javax.swing.JLabel();
        jLabelStockCode = new javax.swing.JLabel();
        jLabelMA5 = new javax.swing.JLabel();
        jLabelMA10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxStartStatus = new javax.swing.JComboBox<>();
        jButtonReset = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemImport = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stocker");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelHigh.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabelHigh.setText("最高：");
        jPanel1.add(jLabelHigh, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, -1));

        jLabelLow.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabelLow.setText("最低：");
        jPanel1.add(jLabelLow, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, -1, -1));

        jLabelOpen.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabelOpen.setText("开盘：");
        jPanel1.add(jLabelOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, -1));

        jLabelClose.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabelClose.setText("收盘：");
        jPanel1.add(jLabelClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, -1, -1));

        jLabelStatus.setFont(new java.awt.Font("隶书", 1, 30)); // NOI18N
        jLabelStatus.setForeground(new java.awt.Color(255, 0, 0));
        jLabelStatus.setText("主上升!");
        jPanel1.add(jLabelStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jTablePoint.getTableHeader().setFont(new java.awt.Font("微软雅黑", 0, 12));
        jTablePoint.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTablePoint.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"上关键点", null, "上关键点", null},
                {"下关键点", null, "下关键点", null},
                {"主上升", null, "主下降", null},
                {"自然回撤", null, "自然回撤", null},
                {"自然回升", null, "自然回升", null},
                {"次级回撤", null, "次级回撤", null},
                {"次级回升", null, "次级回升", null}
            },
            new String [] {
                "上升趋势", "值", "下降趋势", "值"
            }
        ));
        jScrollPane1.setViewportView(jTablePoint);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 330, 142));

        jLabel7.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel7.setText("起始日期：");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, -1));

        jTextFieldStartDate.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTextFieldStartDate.setText("2015/01/04");
        jPanel1.add(jTextFieldStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 80, -1));

        jTextFieldEndDate.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTextFieldEndDate.setText("2016/04/22");
        jPanel1.add(jTextFieldEndDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 80, -1));

        jLabel8.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel8.setText("结束日期：");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, -1, -1));

        jTextAreaMain.setColumns(20);
        jTextAreaMain.setRows(5);
        jScrollPane2.setViewportView(jTextAreaMain);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 650, 80));

        jButtonRead.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jButtonRead.setText("读取");
        jButtonRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReadActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, -1, -1));

        jComboBoxMode.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jComboBoxMode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "收盘价", "5日均线", "10日均线", "20日均线", "30日均线", "60日均线", "K线实体", "K线引线" }));
        jPanel1.add(jComboBoxMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel9.setText("模式：");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, -1, -1));

        jLabelDate.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jLabelDate.setText("日期：----/--/--");
        jPanel1.add(jLabelDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        jButtonContinuous.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jButtonContinuous.setText("连续");
        jButtonContinuous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinuousActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonContinuous, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, -1, -1));

        jCheckBox1.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jCheckBox1.setText("使能V形反转");
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jTextField1.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTextField1.setText("20");
        jTextField1.setEnabled(false);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 30, -1));

        jLabelStockName.setFont(new java.awt.Font("华文行楷", 0, 18)); // NOI18N
        jLabelStockName.setForeground(new java.awt.Color(0, 0, 255));
        jLabelStockName.setText("上证指数");
        jLabelStockName.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.add(jLabelStockName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabelStockCode.setFont(new java.awt.Font("黑体", 0, 16)); // NOI18N
        jLabelStockCode.setForeground(new java.awt.Color(0, 0, 255));
        jLabelStockCode.setText("(000001)");
        jPanel1.add(jLabelStockCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabelMA5.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabelMA5.setText("MA5：");
        jPanel1.add(jLabelMA5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, -1));

        jLabelMA10.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabelMA10.setText("MA10：");
        jPanel1.add(jLabelMA10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, -1, -1));

        jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel1.setText("起始状态：");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        jComboBoxStartStatus.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jComboBoxStartStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "主上升", "主下降" }));
        jComboBoxStartStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxStartStatusActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxStartStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        jButtonReset.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jButtonReset.setText("复位");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 420));

        jMenuFile.setText("文件");

        jMenuItemImport.setText("导入...");
        jMenuItemImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemImportActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemImport);

        jMenuBar1.add(jMenuFile);

        jMenu2.setText("添加");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReadActionPerformed
        String s;
        String[] ss = null;

        try {
            if (fileOpened == false) {
                reset();
                fileReader = new FileReader(fileName);
                bufferedReader = new BufferedReader(fileReader);
                fileOpened = true;
                bufferedReader.readLine();
                bufferedReader.readLine();
            }

            do {
                if ((s = bufferedReader.readLine()) != null) {
                    ss = s.split("\t");
                }
            } while (((s != null) && ss[0].compareTo(jTextFieldStartDate.getText()) < 0));

            if (s != null) {
                updateMarket(s);

                double d = getModeData();
                Livermore(dateString, d);
                updateTable();
                parseStatus();
            } else {
                JOptionPane.showMessageDialog(this, "对不起，没有更多的行情数据了！");
                fileReader.close();
                bufferedReader.close();
                fileOpened = false;
            }
        } catch (IOException e1) {
            e1.printStackTrace();
        }
    }//GEN-LAST:event_jButtonReadActionPerformed

    private void jButtonContinuousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinuousActionPerformed
        String s;
        String[] ss = null;

        if ((jTextFieldEndDate.getText().compareTo(jTextFieldStartDate.getText()) < 0)) {
            JOptionPane.showMessageDialog(this, "起始日期必须早于结束日期！");
            return;
        }

        try {
            reset();
            fileReader = new FileReader(fileName);
            bufferedReader = new BufferedReader(fileReader);
            fileOpened = true;
            bufferedReader.readLine();
            bufferedReader.readLine();

            do {
                if ((s = bufferedReader.readLine()) != null) {
                    ss = s.split("\t");
                    if ((ss[0].compareTo(jTextFieldStartDate.getText()) >= 0) && (ss[0].compareTo(jTextFieldEndDate.getText()) <= 0)) {
                        updateMarket(s);
                        double d = getModeData();
                        Livermore(dateString, d);
                    }
                }
            } while (((s != null) && ss[0].compareTo(jTextFieldEndDate.getText()) < 0));

            parseStatus();
            updateTable();
        } catch (IOException e1) {
            e1.printStackTrace();
        }
    }//GEN-LAST:event_jButtonContinuousActionPerformed

    private void jMenuItemImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemImportActionPerformed
        JFileChooser chooser = new JFileChooser("data/");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Stock Data File (*.txt)", "txt");
        chooser.setFileFilter(filter);
        chooser.setDialogTitle("Select Stock Data File");
        int ret = chooser.showOpenDialog(this);
        if (ret == JFileChooser.APPROVE_OPTION) {
            fileName = chooser.getSelectedFile().getPath();
            System.out.println("Select file: " + fileName);

            try {
                File file = new File(fileName);
                InputStreamReader isr = new InputStreamReader(new FileInputStream(file), "gbk");
                BufferedReader br = new BufferedReader(isr);
                String[] s = br.readLine().split("\t");
                jLabelStockCode.setText("(" + s[0].replaceAll("[\\pP\\p{Punct}]", "") + ")");
                jLabelStockName.setText(s[1]);
                br.close();
                isr.close();
            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_jMenuItemImportActionPerformed

    private void jComboBoxStartStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxStartStatusActionPerformed
        Status = (jComboBoxStartStatus.getSelectedIndex() == 0) ? "mainRiseStatus" : "mainFallStatus";
        parseStatus();
    }//GEN-LAST:event_jComboBoxStartStatusActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        reset();
    }//GEN-LAST:event_jButtonResetActionPerformed

    protected void reset() {
        riseKeyHead = 0;
        riseKeyFoot = 0;
        mainRiseVal = 0;
        normalRiseUVal = 0;
        normalFallUVal = 0;
        minorRiseUVal = 0;
        minorFallUVal = 0;
        fallKeyHead = 0;
        fallKeyFoot = 0;
        mainFallVal = 0;
        normalRiseDVal = 0;
        normalFallDVal = 0;
        minorRiseDVal = 0;
        minorFallDVal = 0;
        updateTable();

        Status = (jComboBoxStartStatus.getSelectedIndex() == 0) ? "mainRiseStatus" : "mainFallStatus";
        parseStatus();

        if (fileOpened) {
            try {
                bufferedReader.close();
                fileReader.close();
                fileOpened = false;
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }

        jTextAreaMain.setText("");
    }

    protected double getModeData() {
        switch (jComboBoxMode.getSelectedIndex()) {
            case 0:
                return Double.parseDouble(closeString);
            case 1:
                return Double.parseDouble(ma5String);
            case 2:
                return Double.parseDouble(ma10String);
            case 3:
                return Double.parseDouble(ma20String);
            case 4:
                return Double.parseDouble(ma30String);
            case 5:
                return Double.parseDouble(ma60String);
            default:
                return Double.parseDouble(closeString);
        }
    }

    protected void parseStatus() {
        switch (Status) {
            case "mainRiseStatus":
                jLabelStatus.setText("主上升！");
                jLabelStatus.setForeground(new java.awt.Color(255, 0, 0));
                break;
            case "normalFallUStatus":
                jLabelStatus.setText("自然回撤");
                jLabelStatus.setForeground(new java.awt.Color(255, 51, 51));
                break;
            case "normalRiseUStatus":
                jLabelStatus.setText("自然回升");
                jLabelStatus.setForeground(new java.awt.Color(255, 51, 51));
                break;
            case "minorFallUStatus":
                jLabelStatus.setText("次级回撤");
                jLabelStatus.setForeground(new java.awt.Color(255, 153, 153));
                break;
            case "minorRiseUStatus":
                jLabelStatus.setText("次级回升");
                jLabelStatus.setForeground(new java.awt.Color(255, 153, 153));
                break;

            case "mainFallStatus":
                jLabelStatus.setText("主下降！");
                jLabelStatus.setForeground(new java.awt.Color(0, 153, 0));
                break;
            case "normalRiseDStatus":
                jLabelStatus.setText("自然回升");
                jLabelStatus.setForeground(new java.awt.Color(51, 255, 51));
                break;
            case "normalFallDStatus":
                jLabelStatus.setText("自然回撤");
                jLabelStatus.setForeground(new java.awt.Color(51, 255, 51));
                break;
            case "minorRiseDStatus":
                jLabelStatus.setText("次级回升");
                jLabelStatus.setForeground(new java.awt.Color(153, 255, 153));
                break;
            case "minorFallDStatus":
                jLabelStatus.setText("次级回撤");
                jLabelStatus.setForeground(new java.awt.Color(153, 255, 153));
                break;
            default:
                break;
        }
    }

    protected void updateMarket(String s) {
        String[] ss = s.split("\t");
        int len = ss.length;
        dateString = ss[0];
        openString = ss[1];
        highString = ss[2];
        lowString = ss[3];
        closeString = ss[4];
        ma5String = ss[len - 6];
        ma10String = ss[len - 5];
        ma20String = ss[len - 4];
        ma30String = ss[len - 3];
        ma60String = ss[len - 2];
        ma120String = ss[len - 1];

        jLabelDate.setText("日期：" + dateString);
        jLabelOpen.setText("开盘：" + openString);
        jLabelHigh.setText("最高：" + highString);
        jLabelLow.setText("最低：" + lowString);
        jLabelClose.setText("收盘：" + closeString);
        jLabelMA5.setText("MA5：" + ma5String);
        jLabelMA10.setText("MA10：" + ma10String);
    }

    protected void updateTable() {
        jTablePoint.setValueAt(riseKeyHead, 0, 1);
        jTablePoint.setValueAt(riseKeyFoot, 1, 1);
        jTablePoint.setValueAt(mainRiseVal, 2, 1);
        jTablePoint.setValueAt(normalFallUVal, 3, 1);
        jTablePoint.setValueAt(normalRiseUVal, 4, 1);
        jTablePoint.setValueAt(minorFallUVal, 5, 1);
        jTablePoint.setValueAt(minorRiseUVal, 6, 1);

        jTablePoint.setValueAt(fallKeyHead, 0, 3);
        jTablePoint.setValueAt(fallKeyFoot, 1, 3);
        jTablePoint.setValueAt(mainFallVal, 2, 3);
        jTablePoint.setValueAt(normalFallDVal, 3, 3);
        jTablePoint.setValueAt(normalRiseDVal, 4, 3);
        jTablePoint.setValueAt(minorFallDVal, 5, 3);
        jTablePoint.setValueAt(minorRiseDVal, 6, 3);
    }

    protected void appendValue() {
        jTextAreaMain.append("riseKeyHead:" + riseKeyHead
                + "\t\tfallKeyHead:" + fallKeyHead
                + "\nriseKeyFoot:" + riseKeyFoot
                + "\t\tfallKeyFoot:" + fallKeyFoot
                + "\nmainRiseVal:" + mainRiseVal
                + "\t\tmainFallVal:" + mainFallVal
                + "\nnormalFallUVal:" + normalFallUVal
                + "\t\tnormalFallDVal:" + normalFallDVal
                + "\nnormalRiseUVal:" + normalRiseUVal
                + "\t\tnormalRiseDVal:" + normalRiseDVal
                + "\nminorFallUVal:" + minorFallUVal
                + "\t\tminorFallDVal:" + minorFallDVal
                + "\nminorRiseUVal:" + minorRiseUVal
                + "\t\tminorRiseDVal:" + minorRiseDVal + "\n");
    }

    protected void resetTrendValue() {
        switch (Status) {
            case "mainRiseStatus":
                riseKeyHead = 0;
                riseKeyFoot = 0;
                mainRiseVal = 0;
                normalRiseUVal = 0;
                normalFallUVal = 0;
                minorRiseUVal = 0;
                minorFallUVal = 0;
                break;
            case "mainFallStatus":
                fallKeyHead = 0;
                fallKeyFoot = 0;
                mainFallVal = 0;
                normalRiseDVal = 0;
                normalFallDVal = 0;
                minorRiseDVal = 0;
                minorFallDVal = 0;
                break;
            default:
                break;
        }
    }

    protected void Livermore(String date, double d) {
        switch (Status) {
            case "mainRiseStatus":
                if (d > mainRiseVal) {
                    mainRiseVal = d;
                } else if (d < (mainRiseVal * 0.9)) {
                    Status = "normalFallUStatus";
                    normalFallUVal = d;
                    riseKeyHead = mainRiseVal;
                    jTextAreaMain.append("[" + date + "] " + "进入自然回撤（上升）\n");
                    appendValue();
                }
                break;
            case "normalFallUStatus":
                if (d < riseKeyFoot * 0.95) {
                    Status = "mainFallStatus";
                    resetTrendValue();
                    mainFallVal = d;
                    jTextAreaMain.append("[" + date + "] " + "进入下降趋势！！！\n");
                    appendValue();
                } else if (d < normalFallUVal) {
                    normalFallUVal = d;
                } else if (d > (normalFallUVal * 1.1)) {
                    Status = "normalRiseUStatus";
                    normalRiseUVal = d;
                    riseKeyFoot = normalFallUVal;
                    jTextAreaMain.append("[" + date + "] " + "进入自然回升（上升）\n");
                    appendValue();
                }
                break;
            case "normalRiseUStatus":
                if (d > mainRiseVal) {
                    Status = "mainRiseStatus";
                    mainRiseVal = d;
                    jTextAreaMain.append("[" + date + "] " + "恢复上升趋势！！！\n");
                    appendValue();
                } else if (d > normalRiseUVal) {
                    normalRiseUVal = d;
                } else if ((d >= (normalRiseUVal * 0.9)) && (d < (normalRiseUVal * 0.95))) {
                    jTextAreaMain.append("[" + date + "] " + "注意：上升趋势可能会改变！\n");
                    appendValue();
                } else if (d < (normalRiseUVal * 0.9)) {
                    if (d < riseKeyFoot * 0.95) {
                        Status = "mainFallStatus";
                        resetTrendValue();
                        mainFallVal = d;
                        jTextAreaMain.append("[" + date + "] " + "进入下降趋势！！！\n");
                        appendValue();
                    } else if (d < normalFallUVal) {
                        Status = "normalFallUStatus";
                        normalFallUVal = d;
                        jTextAreaMain.append("[" + date + "] " + "进入自然回撤（上升）\n");
                        appendValue();
                    } else {
                        Status = "minorFallUStatus";
                        minorFallUVal = d;
                        jTextAreaMain.append("[" + date + "] " + "进入次级回撤（上升）\n");
                        appendValue();
                    }
                }
                break;
            case "minorFallUStatus":
                if (d < riseKeyFoot * 0.95) {
                    Status = "mainFallStatus";
                    resetTrendValue();
                    mainFallVal = d;
                    jTextAreaMain.append("[" + date + "] " + "进入下降趋势！！！\n");
                    appendValue();
                } else if (d < normalFallUVal) {
                    Status = "normalFallUStatus";
                    normalFallUVal = d;
                    jTextAreaMain.append("[" + date + "] " + "进入自然回撤（上升）\n");
                    appendValue();
                } else if (d < minorFallUVal) {
                    minorFallUVal = d;
                } else if (d > minorFallUVal * 1.1) {
                    if (d > mainRiseVal) {
                        Status = "mainRiseStatus";
                        mainRiseVal = d;
                        jTextAreaMain.append("[" + date + "] " + "恢复上升趋势！！！\n");
                        appendValue();
                    } else if (d > normalRiseUVal) {
                        Status = "normalRiseUStatus";
                        normalRiseUVal = d;
                        jTextAreaMain.append("[" + date + "] " + "进入自然回升（上升）\n");
                        appendValue();
                    } else {
                        Status = "minorRiseUStatus";
                        minorRiseUVal = d;
                        jTextAreaMain.append("[" + date + "] " + "进入次级回升（上升）\n");
                        appendValue();
                    }
                }
                break;
            case "minorRiseUStatus":
                if (d > mainRiseVal) {
                    Status = "mainRiseStatus";
                    mainRiseVal = d;
                    jTextAreaMain.append("[" + date + "] " + "恢复上升趋势！！！\n");
                    appendValue();
                } else if (d > normalRiseUVal) {
                    Status = "normalRiseUStatus";
                    normalRiseUVal = d;
                    jTextAreaMain.append("[" + date + "] " + "进入自然回升（上升）\n");
                    appendValue();
                } else if (d > minorRiseUVal) {
                    minorRiseUVal = d;
                } else if (d < minorRiseUVal * 0.9) {
                    if (d < riseKeyFoot * 0.95) {
                        Status = "mainFallStatus";
                        resetTrendValue();
                        mainFallVal = d;
                        jTextAreaMain.append("[" + date + "] " + "进入下降趋势\n");
                        appendValue();
                    } else if (d < normalFallUVal) {
                        Status = "normalFallUStatus";
                        normalFallUVal = d;
                        jTextAreaMain.append("[" + date + "] " + "进入自然回撤（上升）\n");
                        appendValue();
                    } else {
                        Status = "minorFallUStatus";
                        minorFallUVal = d;
                        jTextAreaMain.append("[" + date + "] " + "进入次级回撤（上升）\n");
                        appendValue();
                    }
                }
                break;

            case "mainFallStatus":
                if ((d < mainFallVal) || (mainFallVal == 0)) {
                    mainFallVal = d;
                } else if (d > (mainFallVal * 1.1)) {
                    Status = "normalRiseDStatus";
                    normalRiseDVal = d;
                    fallKeyFoot = mainFallVal;
                    jTextAreaMain.append("[" + date + "] " + "进入自然回升（下降）\n");
                    appendValue();
                }
                break;
            case "normalRiseDStatus":
                if ((fallKeyHead != 0) && (d > fallKeyHead * 1.05)) {
                    Status = "mainRiseStatus";
                    resetTrendValue();
                    mainRiseVal = d;
                    jTextAreaMain.append("[" + date + "] " + "进入上升趋势！！！\n");
                    appendValue();
                } else if (d > normalRiseDVal) {
                    normalRiseDVal = d;
                } else if (d < (normalRiseDVal * 0.9)) {
                    Status = "normalFallDStatus";
                    normalFallDVal = d;
                    fallKeyHead = normalRiseDVal;
                    jTextAreaMain.append("[" + date + "] " + "进入自然回撤（下降）\n");
                    appendValue();
                }
                break;
            case "normalFallDStatus":
                if (d < mainFallVal) {
                    Status = "mainFallStatus";
                    mainFallVal = d;
                    jTextAreaMain.append("[" + date + "] " + "恢复下降趋势！！！\n");
                    appendValue();
                } else if (d < normalFallDVal) {
                    normalFallDVal = d;
                } else if ((d <= (normalFallDVal * 1.1)) && (d > (normalFallDVal * 1.05))) {
                    jTextAreaMain.append("[" + date + "] " + "注意：下降趋势可能会改变！\n");
                    appendValue();
                } else if (d > (normalFallDVal * 1.1)) {
                    if (d > fallKeyHead * 1.05) {
                        Status = "mainRiseStatus";
                        resetTrendValue();
                        mainRiseVal = d;
                        jTextAreaMain.append("[" + date + "] " + "进入上升趋势！！！\n");
                        appendValue();
                    } else if (d > normalRiseDVal) {
                        Status = "normalRiseDStatus";
                        normalRiseDVal = d;
                        jTextAreaMain.append("[" + date + "] " + "进入自然回升（下降）\n");
                        appendValue();
                    } else {
                        Status = "minorRiseDStatus";
                        minorRiseDVal = d;
                        jTextAreaMain.append("[" + date + "] " + "进入次级回升（下降）\n");
                        appendValue();
                    }
                }
                break;
            case "minorRiseDStatus":
                if (d > fallKeyHead * 1.05) {
                    Status = "mainRiseStatus";
                    resetTrendValue();
                    mainRiseVal = d;
                    jTextAreaMain.append("[" + date + "] " + "进入上升趋势！！！\n");
                    appendValue();
                } else if (d > normalRiseDVal) {
                    Status = "normalRiseDStatus";
                    normalRiseDVal = d;
                    jTextAreaMain.append("[" + date + "] " + "进入自然回升（下降）\n");
                    appendValue();
                } else if (d > minorRiseDVal) {
                    minorRiseDVal = d;
                } else if (d < minorRiseDVal * 0.9) {
                    if (d < mainFallVal) {
                        Status = "mainFallStatus";
                        mainFallVal = d;
                        jTextAreaMain.append("[" + date + "] " + "恢复下降趋势！！！\n");
                        appendValue();
                    } else if (d < normalFallDVal) {
                        Status = "normalFallDStatus";
                        normalFallDVal = d;
                        jTextAreaMain.append("[" + date + "] " + "进入自然回撤（下降）\n");
                        appendValue();
                    } else {
                        Status = "minorFallDStatus";
                        minorFallDVal = d;
                        jTextAreaMain.append("[" + date + "] " + "进入次级回撤（下降）\n");
                        appendValue();
                    }
                }
                break;
            case "minorFallDStatus":
                if (d < mainFallVal) {
                    Status = "mainFallStatus";
                    mainFallVal = d;
                    jTextAreaMain.append("[" + date + "] " + "恢复下降趋势！！！\n");
                    appendValue();
                } else if (d < normalFallDVal) {
                    Status = "normalFallDStatus";
                    normalFallDVal = d;
                    jTextAreaMain.append("[" + date + "] " + "进入自然回撤（下降）\n");
                    appendValue();
                } else if (d < minorFallDVal) {
                    minorFallDVal = d;
                } else if (d > minorFallDVal * 1.1) {
                    if (d > fallKeyHead * 1.05) {
                        Status = "mainRiseStatus";
                        resetTrendValue();
                        mainRiseVal = d;
                        jTextAreaMain.append("[" + date + "] " + "进入上升趋势！！！\n");
                        appendValue();
                    } else if (d > normalRiseDVal) {
                        Status = "normalRiseDStatus";
                        normalRiseDVal = d;
                        jTextAreaMain.append("[" + date + "] " + "进入自然回升（下降）\n");
                        appendValue();
                    } else {
                        Status = "minorRiseDStatus";
                        minorRiseDVal = d;
                        jTextAreaMain.append("[" + date + "] " + "进入次级回升（下降）\n");
                        appendValue();
                    }
                }
                break;
            default:
                break;
        }
    }

    private double mainRiseVal = 0;
    private double mainFallVal = 0;
    private double normalRiseUVal = 0;
    private double normalFallUVal = 0;
    private double normalRiseDVal = 0;
    private double normalFallDVal = 0;
    private double minorRiseUVal = 0;
    private double minorFallUVal = 0;
    private double minorRiseDVal = 0;
    private double minorFallDVal = 0;

    private double riseKeyHead = 0;
    private double riseKeyFoot = 0;
    private double fallKeyHead = 0;
    private double fallKeyFoot = 0;

    private String dateString = "";
    private String openString = "";
    private String closeString = "";
    private String highString = "";
    private String lowString = "";
    private String ma5String = "";
    private String ma10String = "";
    private String ma20String = "";
    private String ma30String = "";
    private String ma60String = "";
    private String ma120String = "";

    private String Status = "mainRiseStatus";
    private String fileName = "data\\000001.txt";
    FileReader fileReader;
    BufferedReader bufferedReader;
    boolean readFlag = false;
    private boolean fileOpened = false;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonContinuous;
    private javax.swing.JButton jButtonRead;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBoxMode;
    private javax.swing.JComboBox<String> jComboBoxStartStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelHigh;
    private javax.swing.JLabel jLabelLow;
    private javax.swing.JLabel jLabelMA10;
    private javax.swing.JLabel jLabelMA5;
    private javax.swing.JLabel jLabelOpen;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelStockCode;
    private javax.swing.JLabel jLabelStockName;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemImport;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablePoint;
    private javax.swing.JTextArea jTextAreaMain;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldEndDate;
    private javax.swing.JTextField jTextFieldStartDate;
    // End of variables declaration//GEN-END:variables
}
